### ISSUE TITLE
Add functionality to benchmark two programs

### ISSUE THREAD

**Issue by guilhermeleobas** [sharkdp/hyperfine#103]
Hi @sharkdp,

One of the functionalities that I miss on hyperfine is the ability to benchmark two programs and say which one is faster. 

```bash
hyperfine -r 5 "programA.exe < input1" "programB.exe < input2"
```

I don't program in Rust but if there's interest, I can try to scratch something.

**Comment by sharkdp** [comment]
This should already work (see examples in the README)?

**Comment by guilhermeleobas** [comment]
Oh, I wasn't aware of that. Thanks!
