### ISSUE TITLE
align `--output-json` with `--output-csv`

### ISSUE THREAD

**Issue by psteinb** [sharkdp/hyperfine#110]
in version `1.4.0` of hyperfine `--output-json test.json` yields the individual timings, whereas `--output-csv test.csv` does not?

```
$ hyperfine --export-csv test.csv 'sleep 0.2'
Benchmark #1: sleep 0.2
  Time (mean ± σ):     204.6 ms ±   0.8 ms    [User: 0.2 ms, System: 1.1 ms]
  Range (min … max):   203.4 ms … 206.3 ms
 
$ cat test.csv
command,mean,stddev,user,system,min,max
sleep 0.2,0.2046418712378572,0.0008249316314930503,0.00018673571428571428,0.0011437410714285716,0.20336149459500003,0.20626203659500003
```
and the same for json

```
$ hyperfine --export-json test.json 'sleep 0.2'
Benchmark #1: sleep 0.2
  Time (mean ± σ):     204.7 ms ±   0.9 ms    [User: 0.3 ms, System: 1.0 ms]
  Range (min … max):   203.7 ms … 206.6 ms
 
$ cat test.json
{
  "results": [
    {
      "command": "sleep 0.2",
      "mean": 0.20466111425500003,
      "stddev": 0.0008757442708665281,
      "user": 0.00031423571428571424,
      "system": 0.0010083085714285716,
      "min": 0.203659674255,
      "max": 0.20661967825500002,
      "times": [
        0.204063288255,
        0.20453320125500002,
        0.204890268255,
        0.204969739255,
        0.203828842255,
        0.20639345525500002,
        0.20492674625500001,
        0.204334207255,
        0.203659674255,
        0.20429706725500002,
        0.20661967825500002,
        0.204421583255,
        0.20430772825500002,
        0.204010120255
      ]
    }
  ]
}
```

it would be cool, if the 2 would be aligned.

**Comment by sharkdp** [comment]
How would you integrate the invidual timings in the CSV format? Multiple lines are for multiple benchmarks. The columns are for mean, stddev, etc. There is no third axis. We would have to include the individiual timings in a single cell, separated by a different character. I don't think that's really how CSV is meant to be used?

**Comment by sharkdp** [comment]
In my view, the current CSV export is for people who want to quickly create a plot for multiple benchmarks.

The JSON export is for those that want to get all of the information. It is very easy to parse from most programming languages.

I don't really see where this extended / long-format CSV would be needed because I don't know of any tools with native support for this format. I think it would be fairly easy to write a JSON=>long-format CSV exporter as an external tool(?). I definitely wouldn't like to change the current CSV format to a long-format CSV.

**Comment by psteinb** [comment]
the long format is used heavily in the R community (most notably this very popular project [tidyverse](https://www.tidyverse.org/)). But if you don't use that language, I see why this use of CSV is not on your radar. Too bad. I still encourage you to think about changing the flags on top of adapting the help message. I propose,
`--summary-csv` and `--summary-markdown` plus `--export-json` for example. This would make the effect of the flags much more clear IMHO.

**Comment by sharkdp** [comment]
I think I'd like to keep the `--export-*` option names for now. I'd be okay with adding a new `--export-csv-long` (or `--export-long-csv`?) option that would export to the long CSV format. However, I still think that would be better left to an external tool (could be a short python script).

**Comment by sharkdp** [comment]
(for some examples of Python scripts that read `hyperfine`s JSON output, see the [`scripts/`](https://github.com/sharkdp/hyperfine/tree/master/scripts) folder)
