### ISSUE TITLE
Feature request: get specific program phase time

### ISSUE THREAD

**Issue by mikaoP** [sharkdp/hyperfine#135]
A lot of applications have an startup phase where data is initialized before a heavy computation. To get an accurate comparison it would be great if there were some mechanism to get the time only of one part of the program.

**Comment by sharkdp** [comment]
Thank you for the feedback.

How would you imagine something like this being implemented?

Hyperfine is designed to measure the full execution time of a program. If you want something more fine-grained, I'd refer you to language-specific micro benchmarking libraries (Google Benchmark for C++, criterion for Rust and Haskell, etc.).
