### ISSUE TITLE
Ability to measure the speed of part of a command

### ISSUE THREAD

**Issue by Timmmm** [sharkdp/hyperfine#153]
It would be really cool if hyperfine could scan stdout for magic words that tell it when to start/stop timing. For example if I have a benchmark that loads data from disk and then processes it, I don't really care about the time it takes to load from disk. If I could do this:

```
auto data = load_from_disk();
std::cout << "HYPERFINE_START\n";
process(data);
std::cout << "HYPERFINE_STOP\n";
```

That'd be nice!

**Comment by sharkdp** [comment]
Thank you for the feedback. Please see #135
