### ISSUE TITLE
Use $SHELL instead of /bin/sh?

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/hyperfine#16]

**Comment by mqudsi** [comment]
Note that `SHELL` isn't really configured due to issues with how 3rd party software handles changes to it and as such isn't actually set by some shells at all, e.g. zsh or fish, which keep the original value as-is. Probably better to explicitly specify the shell or stick to `sh` otherwise.

ref #61

**Comment by sharkdp** [comment]
Thank you, I didn't know that. Let's focus on #61.
