### ISSUE TITLE
Add --color=auto/never/always option

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/hyperfine#20]

**Comment by doomrobo** [comment]
As a followup, it might be beneficial to have an option that disables all TUI features (e.g, overwriting lines) to make this easier to deploy in an automated setting like CI

**Comment by stevepentland** [comment]
@sharkdp I'm interested in taking this on. I'm just going through the codebase now for how everything is processed. What are your thoughts on the input by @doomrobo? If it is desired, would it be better as a separate issue for tracking purposes?

**Comment by sharkdp** [comment]
> As a followup, it might be beneficial to have an option that disables all TUI features (e.g, overwriting lines) to make this easier to deploy in an automated setting like CI

> What are your thoughts on the input by @doomrobo?

I tend to think that `--color=never` (or the absence of a TTY) should also disable all TUI features, yes. I'd be okay with only two modes:
- All TUI features enabled, including color (if `--color=always` or if `--color=auto` and we detect a TTY)
- All TUI features disabled, no colors (if `--color=never` or if `--color=auto` in the absence of a TTY)

We could also think about renaming `--color` to something different.

> I'm interested in taking this on

Sounds great!

We have implemented the same thing in `fd`, if you want to take a look: https://github.com/sharkdp/fd/blob/1045930dd9a1dcb6058cbf902041d5c2bb31a48f/src/main.rs#L88-L92

**Comment by stevepentland** [comment]
@sharkdp As a preliminary step I've changed option 'color' to 'style' and changed the possible input values to be 'auto', 'basic', and 'full'. With basic corresponding to either never or auto+no tty, and full corresponding to always or auto+tty.

I've just been tracing through where the different areas that perform output are and have a question. When we're in basic mode, then what should be done with the progress bar? Should it just be removed totally or replaced with something else that makes more sense when output over consecutive lines.

Also, I'd like to refactor where the processing of the matches for args are done out of main to another function as it may be prudent to put that logic under test to ensure that future changes don't cause unintended errors.

**Comment by sharkdp** [comment]
> @sharkdp As a preliminary step I've changed option 'color' to 'style' and changed the possible input values to be 'auto', 'basic', and 'full'. With basic corresponding to either never or auto+no tty, and full corresponding to always or auto+tty.

If you like, you could open a PR already. This way, it's easier to discuss the actual implementation.

> what should be done with the progress bar?

I'd be okay with removing it completely.

> Also, I'd like to refactor where the processing of the matches for args are done out of main to another function, as it may be prudent to put it under test to ensure that future changes don't cause unintended errors.

Sounds great. Maybe this should be a separate PR, though.

**Comment by sharkdp** [comment]
Closed via #24
