### ISSUE TITLE
More digits of precision in relative column of markdown export

### ISSUE THREAD

**Issue by nathanchance** [sharkdp/hyperfine#208]
Thank you for this great tool, it is super helpful.

I have only two minor issues/requests and one is already filed as #182. The other is a increased number of digits of precision in the `Relative` column when using `--export-markdown`, as the tool reports two to the console but only one to the `Relative` coliumn of the table. This results in some `1.0` to `1.0` comparisons, as the benchmarks I am doing are not going to be a drastic difference (comparing building the Linux kernel with different version of GCC and Clang).

**Comment by sharkdp** [comment]
Thank you for the feedback. That sounds like a very sensible change!

**Comment by sharkdp** [comment]
Released in [v1.8.0](https://github.com/sharkdp/hyperfine/releases/tag/v1.8.0).
