### ISSUE TITLE
Man page?

### ISSUE THREAD

**Issue by Roguelazer** [sharkdp/hyperfine#212]
I don't suppose anyone has a man page floating around? It'd be great to have as part of packaging this tool...

**Comment by sharkdp** [comment]
No, I don't think anyone wrote a man page. If somebody wants to work on this, I'm happy to include it in `hyperfine` packages.

```
help2man -N -n hyperfine hyperfine > hyperfine.1
```
can serve as a good start.

**Comment by sharkdp** [comment]
Closed via #257 by @cadeef

**Comment by sharkdp** [comment]
Released in [v1.10.0](https://github.com/sharkdp/hyperfine/releases/tag/v1.10.0).
