### ISSUE TITLE
Raw data export

### ISSUE THREAD

**Issue by miasma** [sharkdp/hyperfine#214]
Would be nice to get a more comprehensive log of the benchmark runs for boxplots etc.. Maybe this is already possible, but couldn't figure out how to output this instead of the summary. I know there's 'bench', but I'd recommend hyperfine instead for simple runs since it's more widely available and easier/faster to compile.

**Comment by sharkdp** [comment]
> Maybe this is already possible, but couldn't figure out how to output this instead of the summary.

There are four different `--export-… <FILE>` options which export the results to various formats.

The CSV and JSON exports should hopefully be suited to your task. In particular, the JSON format contains all of the information about the benchmarks. We even have some simple scripts for plotting in this repository.

This is all described in the README: https://github.com/sharkdp/hyperfine#export-results

**Comment by sharkdp** [comment]
@miasma does this work for you?

**Comment by miasma** [comment]
Hi, sorry been too busy. Yes, works for me. I just tested and only realized now that the JSON output differs from the rest. Since I'm forwarding the data to an R script for plotting, I assumed CSV would be the most suitable format.
