### ISSUE TITLE
Provide finer-grained statistics

### ISSUE THREAD

**Issue by jonhoo** [sharkdp/hyperfine#22]
It'd be nice to be able to show other statistics such as the 95th percentile or median runtime. [HdrHistogram](http://hdrhistogram.org/) can record this with relatively little overhead, and there's a pretty good official Rust implementation [here](https://crates.io/crates/hdrhistogram) (I'm one of the maintainers).

**Comment by josephglanville** [comment]
p95/p99/p99.9 values ofcourse would be great but an option to output the entire histogram both in machine consumable format (json/csv) and/or graphically would be amazing.

**Comment by jonhoo** [comment]
@josephglanville You should be able to do all of that with a HdrHistogram. Of course, it does pay some cost of accuracy in order to remain compact, but it's unlikely that users will notice. The exact trade-offs are also easy to control.

**Comment by sharkdp** [comment]
This sounds really interesting.

Is it possible to get reasonable estimates from HdrHistogram even if we only have very few samples (like 10 time measurements)?

**Comment by jonhoo** [comment]
HdrHistogram doesn't actually do any statistical analysis, it just gathers up recorded values in an efficient way. Think of it as keeping a count per bin (e.g., "there have been 3 samples in the range 1-3ms, 2 in 3-5, etc."), but in a "smart" way such that you generally always have good resolution, and the histogram doesn't grow unbounded if you have large discrepancies in the values.

**Comment by jonhoo** [comment]
Which then in turn can give you whatever percentile you want, though obviously not with higher fidelity than what the number of samples provides. There will be a small inaccuracy due to the binning, but it should be marginal.

**Comment by XANi** [comment]
@jonhoo The thing is that (i think) in most cases CLI testing will be used for less than < 100000 iterations, so you will be saving barely any memory while introducing inaccuracies. It might make sense if that was something that activates above certain threshold, but then 1 milion floats takes 8 MB if you wanted to just use "dumb" algorithm so I doubt it is worth it.

**Comment by jonhoo** [comment]
@XANi you're totally right that with few samples the advantages of using HdrHistogram aren't as compelling. That said, the inaccuracies will also likely be very small, and HdrHistogram does present a nice interface for getting percentile values. It would also be (marginally) faster than scanning all the recorded samples after the fact to compute the percentiles.

**Comment by psteinb** [comment]
I personally would love, if the `--output-*` options would store the timing results of each individual run instead of the summary statistics. This way creating histograms and such can be handled downstream by other tools/languages.

**Comment by sharkdp** [comment]
> I personally would love, if the `--output-*` options would store the timing results of each individual run instead of the summary statistics. This way creating histograms and such can be handled downstream by other tools/languages.

This is exactly what the JSON-output option is for. Downstream tools will get all of the benchmarking information from that output, right?

**Comment by psteinb** [comment]
Yes, but #110 then I suggest to rename the flag, such as `--summ-as-csv` 
or so. From interface I cannot infer that json contains ALL the 
measurements and csv doesn't. The help text also doesn't undisclose this:

```
         --export-csv <FILE>
             Export the timing results as CSV to the given FILE.

         --export-json <FILE>
             Export the timing results as JSON to the given FILE.
```

**Comment by sharkdp** [comment]
Ok, good point. Let's clarify things in the `--help` text. I'd like to keep the current names for the command-line options.

**Comment by sharkdp** [comment]
In the spirit of the last few comments, I have created a folder with exemplary Python scripts that can be used to further analyze benchmarks that have been performed with hyperfine:

https://github.com/sharkdp/hyperfine/tree/master/scripts

The [`advanced_statistics.py`](https://github.com/sharkdp/hyperfine/blob/master/scripts/advanced_statistics.py) script, for example, shows median, percentiles and interquartile range.

With this, I'd like to close this ticket, but I'd be really glad to get some feedback on this. If someone has ideas on how to improve or extend these scripts, I'd also be happy to take pull requests.
