### ISSUE TITLE
Spin Icon Is Broken In Windows

### ISSUE THREAD

**Issue by aolszowka** [sharkdp/hyperfine#229]
The "Spin" Icon does not seem to render in Windows Powershell under Windows 10 1903. The Progress Bar However seems to work just fine? Thank you for the tool; this will replace some in-house tooling that performed similar functionality.

![image](https://user-images.githubusercontent.com/2592881/66774559-1578b400-ee7f-11e9-9fef-7b279d1e7703.png)

**Comment by sharkdp** [comment]
That's a shame. I would guess that this is related to the font not having the appropriate Unicode characters. Can this maybe be resolved by choosing another font? One that is able to display these characters:
```
⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏
```

**Comment by aolszowka** [comment]
That would be my guess as well; unfortunately it appears out of the box Windows only gives a limited number of options. Default appears to be Lucida Console (https://docs.microsoft.com/en-us/typography/font-list/lucida-console) which is what the original image was.

Attempting to use Consolas (https://docs.microsoft.com/en-us/typography/font-list/consolas) wasn't much better; but at least we get the "Missing Glyph" Icon:

![image](https://user-images.githubusercontent.com/2592881/66775662-cd0ec580-ee81-11e9-981f-2d93aa398fea.png)

Using NSimSun (https://docs.microsoft.com/en-us/typography/font-list/simsun) and MS Gothic (https://docs.microsoft.com/en-us/typography/font-list/ms-gothic) kinda worked but resulted in each line printing to the console like so:

![image](https://user-images.githubusercontent.com/2592881/66775698-e4e64980-ee81-11e9-8e22-4b0596aed326.png)

**Comment by aolszowka** [comment]
Thinking about this a little more; the easiest solution would be to replace the glyphs:

https://github.com/sharkdp/hyperfine/blob/921f99901854da45dc6b0704c81ccacc5b1c04b7/src/hyperfine/internal.rs#L18

on Windows with the ASCII set:

```
\  |  / 
```

(Or some variation there of)

While not as pretty as the Unicode version at least it would render in even the most difficult environments. The change looks straight forward but unsure if you would want it from a design/product perspective.

I'm fine closing this issue as WONTFIX/BYDESIGN as well.

Thank you again!

**Comment by sharkdp** [comment]
No, that sounds like a viable option. One potential problem is that this will cause a "regression" for other Windows users that work in other terminal emulators (e.g. cygwin, etc.)

**Comment by sharkdp** [comment]
@aolszowka Could you please check if #254 solves this issue for you?

**Comment by sharkdp** [comment]
This has now been released as [v1.10.0](https://github.com/sharkdp/hyperfine/releases/tag/v1.10.0).

**Comment by sharkdp** [comment]
@aolszowka I would really appreciate a comment from your side.

**Comment by aolszowka** [comment]
Hey @sharkdp sorry I've been MIA on this; it looks like this behaves as expected at least in my simple test. We appreciate you applying a fix!
