### ISSUE TITLE
Add basic information about the system which is running a benchmark

### ISSUE THREAD

**Issue by YauhenPylAurea** [sharkdp/hyperfine#233]
It will be great to have information about the system where a benchmark is running in the final output result.

Like the name of the processor, the amount of memory and the name of OS.

Thank you for the great tool.

[//]: # ({"jiraIssueKey":"","analyzers":{"js":0,"cs":0,"java":0,"acr":0}})

**Comment by sharkdp** [comment]
Thank you for the feedback.

I think this would rather belong in a script or an external wrapper. There are so many things that the benchmark times could potentially depend on (not just CPU, also disk speed, network bandwidth, etc.).

**Comment by sharkdp** [comment]
This is being reconsidered in #460
