### ISSUE TITLE
randomize environment variable length

### ISSUE THREAD

**Issue by NotAFile** [sharkdp/hyperfine#235]
As shown in a [paper a while back](https://www.inf.usi.ch/faculty/hauswirth/publications/asplos09.pdf), the size of the environment variables can significantly affect the performance of a program due to knock-on effects on the memory layout.

![image](https://user-images.githubusercontent.com/5447747/67036800-8f799900-f11c-11e9-91c1-b6da8264b2bf.png)

It might be helpful for accuracy to randomize the layout a bit on each run by inserting a value with a random length of say 0-4000 bytes into the environment.

**Comment by sharkdp** [comment]
Thank you very much for the feedback.

I recently watched [this StrangeLoop talk](https://www.youtube.com/watch?v=r-TLSBdHe1A) which referenced the same paper.

I think this would be a great addition to `hyperfine`. It's also really easy to implement. In fact, I already experimented with a hacky version of this that sets such a random-length environment variable in each benchmark iteration. Unfortunately, I couldn't yet find a conclusive example program that experiences a large change in execution time when randomizing the environment.

Here is one example of a simple `raytracer` program.

Without randomization:

![image](https://user-images.githubusercontent.com/4209276/67162815-2b4b1500-f368-11e9-8990-c56467419e8e.png)

With randomization:

![image](https://user-images.githubusercontent.com/4209276/67162816-3140f600-f368-11e9-9672-cc6bbe5fc1fa.png)

It *looks* like the bottom distribution is slightly wider (which is what I would expect), but it's hard to tell.

Do you happen to know of any programs that experience a large effect on layout change? I tried to run the benchmarks references in the paper, but it's not straightforward.

**Comment by sharkdp** [comment]
closed via #241

**Comment by sharkdp** [comment]
.. and released as [v1.10.0](https://github.com/sharkdp/hyperfine/releases/tag/v1.10.0).
