### ISSUE TITLE
Use monospace in markdown output

### ISSUE THREAD

**Issue by aDotInTheVoid** [sharkdp/hyperfine#291]
When outputting the markdown table, the numbers should use monospace to ensure alignment. 

## Current Output

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `python3 norvig_nocache.py` | 1.186 ± 0.013 | 1.161 | 1.252 | 7.0 |
| `python3 norvig_with_cache.py` | 0.789 ± 0.010 | 0.771 | 0.821 | 4.7 |
| `out/v1_naive` | 2.426 ± 0.070 | 2.227 | 2.692 | 14.3 |
| `out/v3_cheep_tricks` | 2.317 ± 0.068 | 2.148 | 2.587 | 13.7 |
| `out/v5_cache_regex` | 0.194 ± 0.002 | 0.191 | 0.206 | 1.1 |
| `out/v7_jemalloc` | 0.169 ± 0.002 | 0.166 | 0.180 | 1.0 |

## Proposed output

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `python3 norvig_nocache.py` | `1.186 ± 0.013` | `1.161` | `1.252` | `7.0` |
| `python3 norvig_with_cache.py` | `0.789 ± 0.010` | `0.771` | `0.821` | `4.7` |
| `out/v1_naive` | `2.426 ± 0.070` | `2.227` | `2.692` | `14.3` |
| `out/v3_cheep_tricks` | `2.317 ± 0.068` | `2.148` | `2.587` | `13.7` |
| `out/v5_cache_regex` | `0.194 ± 0.002` | `0.191` | `0.206` | `1.1` |
| `out/v7_jemalloc` | `0.169 ± 0.002` | `0.166` | `0.180` | `1.0` |

I am willing to implement this if this is a feature you agree with

**Comment by sharkdp** [comment]
The numbers are actually aligned just fine for me (well.. with the font that GitHub uses):

![image](https://user-images.githubusercontent.com/4209276/82698555-4322a880-9c6b-11ea-8d92-0e3ef2194f38.png)

I agree that a monospace font would maybe be more appropriate here, but I kind of like the look of the normal font better.

**Comment by aDotInTheVoid** [comment]
They look aligned for me now as well. I'm not sure if they've changed something or quarantine is making me go crazy. Closing for now as normal does look better
