### ISSUE TITLE
Writing intermediate results

### ISSUE THREAD

**Issue by wenkokke** [sharkdp/hyperfine#306]
Is there currently any way to force hyperfine to write intermediate results, so that I can abort a benchmark without losing all the progress I've made so far? I'm asking, because I've been benchmarking several algorithms with exponential complexity recently, and so sometimes letting the benchmark finish isn't an option.

**Comment by sharkdp** [comment]
Are you talking about the `--export …` options?

There is no option like this, so far.

**Comment by wenkokke** [comment]
Yeah, I'm requesting that the `--export` options (at least the JSON and CSV options) write results to the file as soon as they become available, instead of at the end of the entire benchmark suite.

**Comment by sharkdp** [comment]
Sounds like a good idea to me :+1:

**Comment by BaronVonDrew** [comment]
@sharkdp Hey, I'd love to pick this up and add an 'incremental export' option if you don't mind? I'm fairly new to Rust but think I can give it a go

**Comment by sharkdp** [comment]
Sounds great!

**Comment by negge** [comment]
Hi, I also ran into this issue recently on a long running benchmark.  Do you know when this will be landing?

On a related note, please confirm that the target file is writable _before_ invoking the test.

**Comment by sharkdp** [comment]
> On a related note, please confirm that the target file is writable _before_ invoking the test.

you mean.. before running the first (potentially long-running) benchmark? That sounds like a good idea!

**Comment by sharkdp** [comment]
Released in https://github.com/sharkdp/hyperfine/releases/tag/v1.12.0
