### ISSUE TITLE
WinGet-based installation

### ISSUE THREAD

**Issue by zkat** [sharkdp/hyperfine#307]
It would be really great to be able to install this on Windows through the [windows package manager, `winget`](https://docs.microsoft.com/en-us/windows/package-manager/winget/).

(Sorry, I know I've hit a few of your repos now. I'm just going through my heavily-used Rust tools and making issues like this on your repos because it would be awesome to install them through the native PM ❤️ . Forgive me the slight spam)

**Comment by sharkdp** [comment]
see my comment here: https://github.com/sharkdp/bat/issues/1102

**Comment by sharkdp** [comment]
I'm going to close this, as I don't really see any value in tracking this here. Let me know if someone thinks otherwise.

**Comment by sharkdp** [comment]
@sitiom Thank you. We could probably add install instructions to the readme

**Comment by sharkdp** [comment]
@zkat Does that work for you?

**Comment by zkat** [comment]
yes! Awesome, thank you :)

**Comment by sitiom** [comment]
> @sitiom Thank you. We could probably add install instructions to the readme

Hmm, ok. Still waiting for the Winget Releaser issue to be resolved, though.
