### ISSUE TITLE
Gradient descent with parameterisation

### ISSUE THREAD

**Issue by gsnedders** [sharkdp/hyperfine#320]
It would be great if there were some mode to automatically do gradient descent with a parametrised argument, starting off testing min/max values plus the midpoint and then descending into the quickest parameter. For cases where the potential search space is large, such an automated mode would be fantastic.

**Comment by sharkdp** [comment]
Thank you for your feedback.

That sounds like a very interesting idea, but maybe that should be implemented in an external (Python) script that uses `hyperfine` with its `--export-json <file>` option for intermediate benchmarks. What do you think?

I'd be glad to host such a script in this repository if someone wants to work on that.

**Comment by sharkdp** [comment]
I'm going to close this for now, as I'm not planning to work on this. If someone wants to contribute such a script, that would be highly appreciated.
