### ISSUE TITLE
Feature request: Named commands

### ISSUE THREAD

**Issue by matthew-hollick** [sharkdp/hyperfine#326]
Hi,
Just started using hyperfine, I think it's going to find a permanent place in my toolkit.

I've been using it to test two instances of the same service running on 2 different local ports (the services in question run on remote servers that I have configured SSH tunnels to).

My invocation looks something like:
`hyperfine --export-markdown results.md 'curl localhost:1000/query' 'curl localhost:1001/query' `
The report is not great for sharing - the person(s) I share it with won't know which port refers to which instance. In a few days time I probably won't either.

I would love it if I could name the commands being ran, something like:
`hyperfine --export-markdown results.md --name 'Current platform' 'curl localhost:1000/query' --name 'New platform' 'curl localhost:1001/query' `

Cheers!

**Comment by sharkdp** [comment]
Thank you for the feedback! Sounds like a great idea!

**Comment by sharkdp** [comment]
closed via #330 by @scampi

**Comment by matthew-hollick** [comment]
Brilliant!!!
Many thanks.

**Comment by sharkdp** [comment]
Released in [hyperfine v1.11.0](https://github.com/sharkdp/hyperfine/releases/tag/v1.11.0).
