### ISSUE TITLE
`--style full` and `--style color` do not keep the color output

### ISSUE THREAD

**Issue by tdulcet** [sharkdp/hyperfine#328]
For example, these two commands are output without any color:
```bash
hyperfine --style full 'sleep 0.3' | cat
hyperfine --style color 'sleep 0.3' | cat
```

![image](https://user-images.githubusercontent.com/15305150/95580757-b5164700-09ec-11eb-9b51-e15d371d6890.png)

**Comment by sharkdp** [comment]
Thank you for reporting this. This used to work ... and should be fixed.
