### ISSUE TITLE
arm/arm64 binaries?

### ISSUE THREAD

**Issue by bjoe2k4** [sharkdp/hyperfine#331]
Hey :-)

just wondering, is there any reason not to have arm/arm64 binary releases for hyperfine? (same goes for hexyl and arm64 for fd for completeness).

Thanks for the tools!

**Comment by sharkdp** [comment]
The only reason is that no one added it until now :smile: Should hopefully not be a big problem to adapt the CI/CD files.

**Comment by markusressel** [comment]
I was looking for this too, would definitely be of value to me :)

**Comment by sharkdp** [comment]
ARM binaries are available for [hyperfine v1.11.0](https://github.com/sharkdp/hyperfine/releases/tag/v1.11.0).
