### ISSUE TITLE
Please build arm64 debs

### ISSUE THREAD

**Issue by rossburton** [sharkdp/hyperfine#349]
You build a 32-bit arm but not a 64-bit arm deb. For obvious reasons the 32-bit package won't work on a 64-bit machine:

```
$ sudo dpkg -i hyperfine_1.11.0_armhf.deb
dpkg: error processing archive hyperfine_1.11.0_armhf.deb (--install):
 package architecture (armhf) does not match system (arm64)
```

**Comment by sharkdp** [comment]
We will have to migrate away from Travis to Github Actions soon. When we do this, we can can consider adding 32-bit arm binaries.

**Comment by sharkdp** [comment]
We now build arm64 packages: https://github.com/sharkdp/hyperfine/blob/master/.github/workflows/CICD.yml#L50

I attached the one built for current  `master`, if you are interested.

[hyperfine_1.11.0_arm64.deb.zip](https://github.com/sharkdp/hyperfine/files/6888696/hyperfine_1.11.0_arm64.deb.zip)
