### ISSUE TITLE
Citing Hyperfine

### ISSUE THREAD

**Issue by drewnutt** [sharkdp/hyperfine#353]
What is the preferred method for citation of the hyperfine command line tool in a scientific manuscript?

**Comment by sharkdp** [comment]
Thank you for asking!

Maybe similar to what has been proposed here: https://academia.stackexchange.com/a/14015 ?

If it's up to me, you do not need to include my name.

In any case, I'd be glad to see the final publication! :smiley:

**Comment by sharkdp** [comment]
@drewnutt has this been resolved? Has your manuscript been published anywhere yet?

**Comment by drewnutt** [comment]
Yes, this has been resolved. The manuscript was published: [https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00522-2](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00522-2). Thank you for the awesome tool.

**Comment by sharkdp** [comment]
That is so cool. Thank you for the citation and best wishes for your publication!
