### ISSUE TITLE
How to use Hyperfine as a regression testing benchmark?

### ISSUE THREAD

**Issue by zachriggle** [sharkdp/hyperfine#361]
I would like to perform regression testing of some of my tools, which requires checking out multiple different Git tags, but always running the same command.  Checking out the Git tag as part of the benchmark adds to the benchmark time, so that doesn't work.

Is there any support for doing something like this?

**Comment by sharkdp** [comment]
Yes. You can use the `--prepare <CMD>` option to do your git checkout (and other setup work).

**Comment by shepmaster** [comment]
In similar cases, I use git rebase's `exec` capability to execute code like this:

```
exec cargo build --release && hyperfine -w 5 -m 25 './target/release/dump ../examples/standard.xml > /tmp/dump-log'
pick 8e0c0fb make it go faster one
exec cargo build --release && hyperfine -w 5 -m 25 './target/release/dump ../examples/standard.xml > /tmp/dump-log'
pick 4d778d5 make it go faster two
exec cargo build --release && hyperfine -w 5 -m 25 './target/release/dump ../examples/standard.xml > /tmp/dump-log'
```

**Comment by sharkdp** [comment]
> In similar cases, I use git rebase's `exec` capability to execute code like this:

Oh, nice. I didn't know `git rebase` had an `--exec` option. That seems very helpful.

What I have done in the past to find performance regressions was to use `git bisect`. If `hyperfine` had an option like `--fail-if-larger-than`, we could even use `git bisect run` to automatically find the regression using a binary search. Assume that v1.0 took 2 seconds and v1.3 took 4 seconds:
``` bash
git bisect start
git bisect good v1.0
git bisect bad v1.3
git bisect run hyperfine "./my-benchmark" --fail-if-larger-than 3s
```

**Comment by sharkdp** [comment]
@zachriggle Has this been resolved?

**Comment by sharkdp** [comment]
See also the section on Chronologer here: https://github.com/sharkdp/hyperfine#integration-with-other-tools
