### ISSUE TITLE
Expose timer as a crate

### ISSUE THREAD

**Issue by kuviman** [sharkdp/hyperfine#367]
I was looking for an easy way to calculate cpu times for child processes in Rust, and the only cross platform option I have found is the timer module of this repository. I think it would be great if it was exposed as a separate crate for people to use.

**Comment by sharkdp** [comment]
Thank you for the feedback. Sounds like a good idea! I'm not sure when/if I will get around to it though.

If someone wants to help, I would appreciate if we could first keep everything inside this repository, but prepare the code for extraction into a new crate (proper `pub` usage, documentation, tests, etc.). We could even move it into a separate crate within this repository.

**Comment by sharkdp** [comment]
@kuviman Are you still interested in having this as a crate? Otherwise, I'd like to close this ticket.

Note that the hyperfine timer currently has a problem with user/system times on Windows (#368).

**Comment by kuviman** [comment]
I do still think that exposing as a crate would be useful. I myself did not need that functionality for long time but I might in the near future.

If I do look at it I may try and do this myself and make a PR here. This would involve fixing #368 too

If noone else is interested I guess you can close this but I think there is still no alternatives?

Also, if I remember correctly, I looked briefly at the code and I think this would require more work than just extracting the module into a crate to make it more general-purpose. I think on unix this calculates times of the whole process tree including the hyperfine process itself but I would only like to see info of a single particular child (sub-tree).

So maybe this is not proper place for this issue anyway, since you don't really need this for hyperfine, but as I said, having such functionality somewhere would be great

**Comment by sharkdp** [comment]
I recently restructed the code base and cleaned up a lot, including the `timer` module. Now might be a good time to reconsider this.

**Comment by sharkdp** [comment]
Closing this for now, as I'm not going to work on this myself. And there seems to be little interest.
