### ISSUE TITLE
Add Custom Timers/Parse Function

### ISSUE THREAD

**Issue by acminor** [sharkdp/hyperfine#370]
Sometimes it is useful to have custom in-program timers not matching the program runtime. For example, I might want to time the time it takes to compute something on the GPU and the time it takes to copy the computed data to the CPU. So I would have two timers, both not being the "real" time.

I might output the results as the following

| Compute Time | Copy Time |
| 1.032                | 1.3235        |

As hyperfine already has shell support, it would be nice to do the following

hyperfine --(OPTIONS FOR PROGRAM) --parse-fn "perl (SOME EXPRESSION TO GET TIMES)"

Then have the output times follow some safe format for separating multiple clocks.

I have not tried this yet, but I have a hunch that I can do something (hacky) but similar by using the --prepare option for running the program and then running a script to wait the amount of time my program timer ran for; however, this has the bad consequence of roughly doubling the time it takes to execute a benchmark because of the need to double count times.

**Comment by sharkdp** [comment]
Thank you for your request. Have you seen #170?

**Comment by acminor** [comment]
I had not seen that issue. Thanks for pointing that out. I understand you wanting to keep the project scope narrow.

**Comment by acminor** [comment]
Should I close or you?
