### ISSUE TITLE
Multiple markdowns from different tests

### ISSUE THREAD

**Issue by InfRandomness** [sharkdp/hyperfine#376]
Hi;

I am using hyperfine to test some of my software against some other software and I would like to know if it's possible to get a feature that would allow me (or us) to merge different markdown files into one;
or to have the possibility to generate one single markdown file instead that would have two columns referencing the data for each tests (would make that easier if you are trying to compare two different test set's results)

(I am not sure if my wall of text is clear and understand, please let me know and I will try to explain what I have on my mind a little bit better)

**Comment by sharkdp** [comment]
Thank you for your request. A simplified example would be great.

**Comment by InfRandomness** [comment]
Hi;

Basically I would like to see the ability to merge the result of different tests in the same markdown file to do some comparative documentations, this would be great;

**Comment by sharkdp** [comment]
How should the output look like?

**Comment by InfRandomness** [comment]
I don't really have an idea on how to structure that but I can give a use case that would probably help structuring things out : 
I am using hyperfine to test my programs against different datasets, so I have a big dataset, a regular sized dataset and a small dataset, and I have a bash script that uses hyperfine to test against the three different dataset sizes, and then I use hyperfine to test another program against these same datasets;

**Comment by InfRandomness** [comment]
no that would be fine

**Comment by requiem958** [comment]
I add this problem while using hyperfine to benchmark multiple different commands, so i wrote some little python script 

[https://gist.github.com/requiem958/fa3f9bf9173bde8bafd0e69582a84b33](https://gist.github.com/requiem958/fa3f9bf9173bde8bafd0e69582a84b33)

It recomputes some data, but this was because i add to merge with another tool which does not output the same, if you just want to merge, you can just keep the loop as:

```python
for r in json_object["results"]:
        result_json["results"].append(r)
```

**Comment by sharkdp** [comment]
Thanks.

I think this issue can be closed.
