### ISSUE TITLE
[FR] Allow caching of the shell startup time

### ISSUE THREAD

**Issue by NightMachinary** [sharkdp/hyperfine#378]
I don't know what algorithm hyperfine uses to determine how many samples to draw for determining the shell startup time, but when I use my custom "shell" that sends the code to my (local) REST server to be evaled, hyperfine takes a few seconds to determine the shell startup time (the commands execute fast themselves). I think that if hyperfine just caches this measurement for later reuse, it would make this workflow that much faster.

**Comment by sharkdp** [comment]
`hyperfine` currently uses a fixed amount of 200 shell startup invocations, which is probably quite a bit too high. I'm not a big fan of implementing a caching mechanism for this, as there would be no way to know when to invalidate it. A new version of the shell might have been installed or something else in the environment could have changed. Alternatively, we could either:
- Reduce that standard amount to maybe 50?
- Provide a new command-line option to specify the amount (`--shell-spawn-time-runs <NUM>` or similar).
- Do both of the above.

What do you think?

**Comment by sharkdp** [comment]
> The startup time should not change noticeably because of upgrades, etc, I think.

I disagree. There are so many factors that can influence benchmark performance: Background processes, the CPU might be throttled (laptop on battery, slowdown due to thermal problems, …), hardware might change (disk, CPU), environment variables might change, the actual shell executable might change, …

Even if those might only end up being tiny effects, I would never trust the cached shell startup times. And even if - it would be very hard to teach users to use `--refresh-cache` correctly.

May I ask: What is the startup time of your shell? My `sh` starts in 2.1 ms. Even when running 200 benchmark runs for calibration, the total shell startup measurement time is below 0.5 seconds.

**Comment by NightMachinary** [comment]
```
❯ time2 brishz_para.dash true          


Took 0.19729399681091309

❯ x 0.2*200          
40.0
```

I was thinking of the cache being per SHELL, but I guess your proposal is ultimately better, and solves my problem. So let's go with that.

**Comment by sharkdp** [comment]
:+1: 

Maybe for your use case, you would be better off by performing two benchmarks. One for the (long) startup time of the shell (by running an empty command). And another for the actual full (shell startup + cmd) time. Then subtract the former from the latter.

This has the added advantage that you can check if your results are statistically significant. If the error on the shell startup time is on the same order of magnitude as (or larger than) the command runtime, your results are not reliable.

**Comment by dgrunwald** [comment]
I could also use this: as-is, the "measuring shells spawning time" phase takes 20 seconds for me.

I'm on Windows with cmd.exe and have [clink](https://mridgers.github.io/clink/) installed. This seems to mean that every shell has to start up a helper clink process, which isn't fast.

**Comment by dgrunwald** [comment]
Actually now that I thought about this, I have an easy solution for my clink issue: `clink autorun --uninstall` and instead configure Windows Terminate to inject clink into new tabs. That way clink only starts for interactive shells and not every shell.

Still, even then cmd.exe isn't exactly the fastest shell around:
```
Benchmark #1: cmd.exe                                                                                                                                                                          0
  Time (mean ± σ):      11.2 ms ±   0.5 ms    [User: 1.4 ms, System: 4.6 ms]                                                                                                                   0
  Range (min … max):    10.3 ms …  12.7 ms    149 runs
```

I know GNU Make has a hack on Windows where it tries to detect whether the command-line involves any special shell characters like `|`, or `&`, and if it doesn't, make bypasses the shell and executes the target program directly.

**Comment by sharkdp** [comment]
> On Windows it might be a good idea to bypass the shell when possible and directly start the target program (on Windows, parsing the command-line into an argument list is done by the started program, not by the shell. The shell is only necessary when pipes or operators like `&&` are involved)

I agree. See also: #336 




> Actually now that I thought about this, I have an easy solution for my clink issue: `clink autorun --uninstall` and instead configure Windows Terminal to inject clink into new tabs. That way clink only starts for interactive shells and not every shell.

:+1: 


> Still, even then cmd.exe isn't exactly the fastest shell around:

Okay. I think we can easily reduce the number of shell invocations to say 50. This would result in an overhead of half a second, which sounds good to me.



> I know GNU Make has a hack on Windows where it tries to detect whether the command-line involves any special shell characters like `|`, or `&`, and if it doesn't, make bypasses the shell and executes the target program directly.

Related comment: https://github.com/sharkdp/hyperfine/issues/336#issuecomment-711047129
