### ISSUE TITLE
Add export options

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/hyperfine#38]
It would be great if we could export benchmark results in different formats:

* Markdown for easy integration into README files
* JSON for further processing
* CSV for simple plotting (gnuplot) -- header + one line per benchmark with columns `mean, stddev, min, max`

Each of those could be new command line options (`hyperfine --export-csv my-benchmark.csv`).

**Comment by stevepentland** [comment]
@sharkdp I'll take this on one. Do we want to split this into multiple sub-tasks for output type? That will allow for incremental progress. And, when specified, will we retain all standard terminal output also?

**Comment by sharkdp** [comment]
> Do we want to split this into multiple sub-tasks for output type?

Sounds good. We can still keep this one for now to discuss the general plan.

> And, when specified, will we retain all standard terminal output also?

Yes, I think so. In addition, we would collect all results in some data structure and then write everything to the specified file at the end of the benchmark.

**Comment by sharkdp** [comment]
Closed via #41. Markdown and JSON export can be tracked separately.
