### ISSUE TITLE
Add Pacstall installation method for Ubuntu

### ISSUE THREAD

**Issue by wizard-28** [sharkdp/hyperfine#400]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. I am the maintainer of the [hyperfine-bin](https://github.com/pacstall/pacstall-programs/blob/master/packages/hyperfine-bin/hyperfine-bin.pacscript) pacscript in this [repository](https://github.com/pacstall/pacstall-programs).

It can be installed on Ubuntu by running this command (After Pacstall is installed)
```bash
sudo pacstall -I hyperfine-bin
```

---

It can also be upgraded
```bash
sudo pacstall -Up
```
and removed when requested.
```
sudo pacstall -R hyperfine-bin
```
---

This downloads the latest release `hyperfine-v1.11.0-x86_64-unknown-linux-musl.tar.gz` and installs every file in the right directory (man page, auto completions, binary, license and the README) automatically.

So, can you add this installation method in the README.md for Ubuntu?

*PS: I am working to add hyperfine (compiles from the latest release source code) and hyperfine-git (clones and compiles the git repo) in the future*

**Comment by sharkdp** [comment]
Thank you! Sounds good to add it to the README. A PR would be appreciated.

**Comment by sharkdp** [comment]
Closing for now, see comment in #401.
