### ISSUE TITLE
--shell 'busybox sh', 'zsh --emulate posix', 'bash --posix'

### ISSUE THREAD

**Issue by mralusw** [sharkdp/hyperfine#410]
It seems that `--shell` needs to be a single word -- which makes it impossible, amongst others, to test `busybox sh` or `zsh --emulate sh` or `bash --posix`.

Sure, for busybox you can symlink, and for zsh / bash, I suppose you can create a stub script (or small C wrapper) that `exec's` the real shell with prepended options. But of course **that perturbs the measurement**.

It might make sense to do simple whitespace splitting of the provided shell string. At most, we might have to handle '`\ `' (to allow for shell executables with whitespaces in their paths). Or we could try looking up the shell in `$PATH` first (like it's currently done), then if that fails, try whitespace splitting.

**Comment by sharkdp** [comment]
Thank you for reporting this. This should be fixed.

> It might make sense to do simple whitespace splitting of the provided shell string. At most, we might have to handle '`\ `' (to allow for shell executables with whitespaces in their paths). Or we could try looking up the shell in `$PATH` first (like it's currently done), then if that fails, try whitespace splitting.

We can use `shell-words` (https://crates.io/crates/shell-words). See also: #336

**Comment by rhysd** [comment]
I'll work on this.

**Comment by sharkdp** [comment]
Please take note of https://github.com/sharkdp/hyperfine/pull/429 which also touches similar parts of the code base
maybe it makes sense to merge #429 first or to base your changes on this branch.

**Comment by rhysd** [comment]
@sharkdp Ah, I already created a PR #436.

**Comment by rhysd** [comment]
Can we merge #436 at first then request #429 author to merge the main branch?
