### ISSUE TITLE
Export to JSON

### ISSUE THREAD

**Issue by stevepentland** [sharkdp/hyperfine#42]
This covers exporting results to JSON as outlined in #38 and extends on the work done on #41.

The same format of --export-xxx should be used (in this case --export-json) with a filename parameter following. It should exist peacefully with simultaneous usage of --export-csv and multiple instances of both.

**Comment by sharkdp** [comment]
Something I would like to see for the JSON export (probably not for the CSV export) is a list of all measured times. These could be listed in addition to the statistical properties. What do you think?

(this is something we can also add at a later stage, let's focus on #41 first)

**Comment by stevepentland** [comment]
Sure, that can also be added on once the generic export mechanisms are hammered out. Since we're using serde, there may actually be some facility to ignore a field or set of fields for a given export type.

**Comment by sharkdp** [comment]
Closed via #45 and #48

**Comment by sharkdp** [comment]
A small Python script that can be used to plot benchmark results, given a exported JSON file:

https://gist.github.com/sharkdp/e1712590690aa95df65f5a73751d33a9
