### ISSUE TITLE
Export to Markdown

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/hyperfine#44]
Add a `--export-markdown` option in analogy to #41 for CSV and #42 for JSON.

The output could look like this:

``` md
| Benchmark | Mean [ms]   | Min. [ms] | Max. [ms] |
|-----------|-------------|-----------|-----------|
| command 1 | 205.1 ± 1.5 | 201.1     | 207.6     |
| command 2 | 403.5 ± 2.4 | 400.3     | 407.4     |
```

Rendered:

| Command   | Mean [ms]   | Min. [ms] | Max. [ms] |
|-----------|-------------|-----------|-----------|
| command 1 | 205.1 ± 1.5 | 201.1     | 207.6     |
| command 2 | 403.5 ± 2.4 | 400.3     | 407.4     |

**Comment by stevepentland** [comment]
I've started looking at this and it seems like we're going to implement this one by hand. There's been nothing I've seen that will do this form of serialization by default, and nothing in particular that will integrate with serde.

**Comment by sharkdp** [comment]
Using something like https://docs.rs/comrak/0.2.8/comrak/ could work (create an AST that represents the table and pretty-print it via [`format_commonmark`](https://docs.rs/comrak/0.2.8/comrak/fn.format_commonmark.html).

On the other hand, maybe the easiest option for now would be to simply `write!` the markdown table by hand. It doesn't necessarily have to look pretty in the source file.

**Comment by stevepentland** [comment]
True, in our case simply creating the encoded values ourselves will probably be best as it is rather simple. I'll move into that next since #45 is now ready

**Comment by stevepentland** [comment]
@sharkdp I've completed this in my [export-markdown](https://github.com/stevepentland/hyperfine/tree/export-markdown) branch. I'll make a PR once #45 has been merged

**Comment by sharkdp** [comment]
Looks great! Maybe we could add backticks ("`") around the command?

**Comment by stevepentland** [comment]
Missed you comment, adding it now
