### ISSUE TITLE
Implicitly or optionally add any -L variables to the command name if the <command> is constant (but -p is not)

### ISSUE THREAD

**Issue by avar** [sharkdp/hyperfine#444]
Hyperfine's summary of the command being executed is good if you do e.g.:

    hyperfine -L jobs 1,8 'make -j {jobs}'

But I often find myself writing a one-liner where `-p` sets up a different runtime environment, but the `<command>` is constant, e.g.:

    hyperfine -L r ,~ -p 'git checkout HEAD{r} -- Makefile' 'make' -c 'git checkout HEAD -- Makefile'

In this case hyperfine's output will be say (here the performance numbers don't matter):

```
Summary
  'make' ran
    1.04 ± 0.03 times faster than 'make'
```

I.e. the command is just `make`. That's correct, but not very useful. The `{r}` in the `-p` was different. I'd like it to instead emit e.g.:

```
Summary
  'make' with r=`` ran
    1.04 ± 0.03 times faster than 'make' with r=`~`
```

Or similar, i.e. stick the relevant variables that were different in there somehow.

Now I tend to use something like this as a workaround, i.e. stick an 'echo {r}' or similar in there somewhere. This is the same as the above except for adding an `echo r={r} &&` prefix to the `<command>`:

    hyperfine -L r ,~ -p 'git checkout HEAD{r} -- Makefile' 'echo r={r} && make' -c 'git checkout HEAD -- Makefile'

Which gives us:

```
Summary
  'echo r= && make' ran
    1.03 ± 0.03 times faster than 'echo r=~ && make'
```
Thanks for working on `hyperfine`! We're starting to use it a lot over at https://github.com/git/git.git. Cloning it and doing `git log --grep=hyperfine` will show some recent uses of it.

**Comment by sharkdp** [comment]
Thank you very much for your feedback. This sounds like a very reasonable request.



> Thanks for working on `hyperfine`! We're starting to use it a lot over at https://github.com/git/git.git. Cloning it and doing `git log --grep=hyperfine` will show some recent uses of it.

Cool! Thank you for mentioning it.

**Comment by sharkdp** [comment]
This can actually be solved with `--command-name`, right?

Something like:
```
hyperfine \
  -L branch master,feature1,feature2 \
  -p 'git checkout {branch}' \
  'make' \
  --command-name 'compile time on branch {branch}'
```

**Comment by sharkdp** [comment]
I'm closing this for now. Please feel free to comment in case it should be re-opened.
