### ISSUE TITLE
Difference between markdown and asciidoctor output

### ISSUE THREAD

**Issue by khmarbaise** [sharkdp/hyperfine#452]
I have run the following command:
```
$ hyperfine -w 1 --export-markdown ../results.md -L VERSION 3.0.5,3.1.1,3.8.4 -n "{VERSION}"  "../apache-maven-{VERSION}/bin/mvn clean"
```
which results in `results.md`
```
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `3.0.5` | 1.315 ± 0.054 | 1.215 | 1.398 | 1.03 ± 0.07 |
| `3.1.1` | 1.272 ± 0.062 | 1.185 | 1.398 | 1.00 |
| `3.8.4` | 1.533 ± 0.266 | 1.386 | 2.284 | 1.20 ± 0.22 |
```
Furthermore I have run the following command:
```
$ hyperfine -w 1 --export-asciidoc ../results.adoc -L VERSION 3.0.5,3.1.1,3.8.4 -n "{VERSION}"  "../apache-maven-{VERSION}/bin/mvn clean"
```
which results into `results.adoc`:
```
[cols="<,>,>"]
|===
| Command | Mean [s] | Min…Max [s]

| `3.0.5`
| 1.393 ± 0.031
| 1.337…1.434

| `3.1.1`
| 1.412 ± 0.045
| 1.350…1.471

| `3.8.4`
| 1.524 ± 0.056
| 1.438…1.607
|===
```
The asciidoctor output lacks the column `Relative` also have different content/columns in comparison to the markdown output...

Is there a good reason why asciidoctor output and markdown output differ?

**Comment by sharkdp** [comment]
> The asciidoctor output lacks the column `Relative` also have different content/columns in comparison to the markdown output...
> 
> Is there a good reason why asciidoctor output and markdown output differ?

No. I think the asciidoctor format hasn't been updated in a while and might lack some details. This should be fixed.
