### ISSUE TITLE
Feature Request: additional fields

### ISSUE THREAD

**Issue by ondohotola** [sharkdp/hyperfine#460]
Hi,

I am using hyperfine to compare a latex run on different machines. I can easily grab all the result files and pull the data out into one, but that information does not contain stuff like  "date", "machine" type,  and "processor", stuff I can easily grab at runtime with commands like

`system_profiler SPHardwareDataType|awk -F': ' '$1 ~ /Model Identifier/ {print $2}'` 
which gives MacBookPro16,2 (posing additional issues with CSV :-)-O) and

`uname -a | awk '{print $NF}'`
which gives 'x86_64' or 'arm64'

`uname -a | awk '{print $3}'` 
which gives 21.1.0 

and of course 
`date +%F`

If someone has an idea how to achieve this within a Makefile for the CSV type it would also be helpful, but since this might be helpful to others perhaps this should then also work in JSON and the other formats (if possible).

thanks in advance, el

**Comment by sharkdp** [comment]
That sounds like a useful feature request, thank you!

I actually implemented a cross-platform library recently that can collect information like this (https://github.com/sharkdp/bugreport). It's designed for bug reports but it could probably be split into two libraries: one for collecting the information and the other for providing the "bugreport"-functionality.

**Comment by ondohotola** [comment]
David,

great to hear that this request is helpful.

el

**Comment by sharkdp** [comment]
Closing this in favor of #711
