### ISSUE TITLE
Add build from source instructions

### ISSUE THREAD

**Issue by JMuff22** [sharkdp/hyperfine#466]
I suggest adding some options to build from source

1. Clone the repository and `cd` into it

2. Install Rust + Cargo on linux and macOS if not already installed with
``
curl https://sh.rustup.rs -sSf | sh
``
3. Build with 
``
cargo build 
``

The `hyperfine` binary is then found under the `/target/` directory, which can be added to your `$PATH` if you wish.

This is merely a suggestion as an alternate way to use hyperfine.
Thanks.

**Comment by sharkdp** [comment]
Sounds good! Any help would be appreciated.

**Comment by sharkdp** [comment]
We actually have instrutions for this already: https://github.com/sharkdp/hyperfine#with-cargo-linux-macos-windows

I just updated the section to include the words "from source".




> 3\. Build with
>         `cargo build `

Note that this will give you a debug build. Use `cargo build --release` to get an optimized build. `cargo install` will do this automatically.
