### ISSUE TITLE
Cannot run with Node.js files

### ISSUE THREAD

**Issue by 0xdw** [sharkdp/hyperfine#499]
### Description
When using hyperfine with NodeJS, it prompts an error as attached below.

> hyperfine 1.13.0
> Windows 11

### Command
```shell
hyperfine native.js normal.js
```

### Source Files
```js
// native.js
const fs = require("fs")
fs.writeFileSync("native", 1, "utf8")
```

```js
// normal.js
const fs = require("fs")
fs.writeFileSync("normal", 1, "utf8")
```

### The prompt
![image](https://user-images.githubusercontent.com/12568779/163037367-9a0e020a-81e3-4e66-9ccc-571e40a415df.png)

### After press the ok button
![image](https://user-images.githubusercontent.com/12568779/163037422-8c01650c-c867-46f5-b770-b391f0b50c96.png)

**Comment by sharkdp** [comment]
Can you start those programs by simply running "native.js" on the console? I would expect that you need to prefix with "node"? Can you try
```bash
hyperfine "node native.js" "node normal.js"
```
or
```bash
hyperfine ./native.js ./normal.js
```

**Comment by 0xdw** [comment]
Running `hyperfine "node native.js" "node normal.js"` fixed the issue.

I think the syntax error was the `require`.  So, what about making it automatically detect and re-adjust the command by the library itself? Just a suggestion :)

Thanks,

![image](https://user-images.githubusercontent.com/12568779/163809628-4df13752-69b5-4cfe-af6b-c95790f3cb59.png)

**Comment by sharkdp** [comment]
> I think the syntax error was the `require`. So, what about making it automatically detect and re-adjust the command by the library itself? Just a suggestion :)

This is not something that hyperfine is going to fix, it's a general problem. You can not simply execute a JavaScript file using your shell. On Linux, you can use shebangs (https://en.wikipedia.org/wiki/Shebang_(Unix)) to tell the shell what interpreter to launch. Not sure if that is possible on Windows as well.
