### ISSUE TITLE
Add ability to measure user and system time

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/hyperfine#5]
Just like time(1):
``` bash
$ /bin/time -p fd -HI -e jpg '' ~ > /dev/null
real 1.41
user 4.23
sys 2.89
```

**Comment by hmenke** [comment]
`time` on Linux uses `procfs` to obtain this info.  There is a crate for this [`procinfo`](https://docs.rs/procinfo/0.4.2/procinfo/pid/struct.Stat.html) but this of course does not work on Mac OS.
