### ISSUE TITLE
Option to show mean time or absolute difference in summary

### ISSUE THREAD

**Issue by SheetJSDev** [sharkdp/hyperfine#531]
Currently summary shows relative difference (ratio +/- dev).  Ideally some sort of absolute time would be shown in the summary.  A few options include

1) show the actual means in the summary:

```
  'bun bun.js' (55.7 ms) ran
    1.88 ± 0.07 times faster than 'node node.mjs' (104.6 ms)
    3.94 ± 0.12 times faster than 'deno run --allow-all deno.ts' (219.7 ms)
```

2) show the difference and optionally the standard error between the sets of runtimes:

```
  'bun bun.js' ran
    1.88 ± 0.07 times (48.9 ms) faster than 'node node.mjs'
    3.94 ± 0.12 times (164.0 ms) faster than 'deno run --allow-all deno.ts'
```

**Comment by sharkdp** [comment]
Thank you. I think I like option two better. I'm just not sure if it really helps that much or if it makes the output of hyperfine even more intimidating for newcomers?

**Comment by sharkdp** [comment]
Closing this for now.
