### ISSUE TITLE
Implement p75, p99 like bombardier

### ISSUE THREAD

**Issue by xHyroM** [sharkdp/hyperfine#537]

**Comment by xHyroM** [comment]
oh, i think its in `times` array already

**Comment by sharkdp** [comment]
percentiles are also computed here

https://github.com/sharkdp/hyperfine/blob/6c0ec317ead302ce7b3e79d944d0a8315d758ad8/scripts/advanced_statistics.py#L18-L21

You can show them by running that script on your benchmark.json file.
