### ISSUE TITLE
User time and kernel time are always shown in the same unit as the corresponding mean (or max) time

### ISSUE THREAD

**Issue by jeremie-martin** [sharkdp/hyperfine#539]
The user and sys time of a multi-threaded program can be greater than 1s, even though its execution can takes less than 1s. Wouldn't it make sense to print these in *s* instead of *ms*?

![pic-selected-220815-1308-23](https://user-images.githubusercontent.com/6959706/184625631-23b2818d-2b51-40ba-bc7e-282abaf11de3.jpg)

**Comment by sharkdp** [comment]
> The user and sys time of a multi-threaded program can be greater than 1s, even though its execution can takes less than 1s.

Good point.

> Wouldn't it make sense to print these in _s_ instead of _ms_?

Hm. Do you really think that would be better? I tried to keep the units consistent (at least for one benchmark) in order to make them easier to compare.

**Comment by jeremie-martin** [comment]
>Do you really think that would be better? I tried to keep the units consistent (at least for one benchmark) in order to make them easier to compare.

The current approach is indeed quite consistent. By no mean using the same units on the same line is a bad choice. Seeing `1978.6 ms` did surprise me though. I only have four cores, but with modern processors (and HPCs) we could get results with an additional digit. It's kind of an edge case, but I don't think it makes them easy to read.

Here is another example, with the output of `hyperfine 'sleep 1'`:
```
Time (mean ± σ):      1.006 s ±  0.002 s    [User: 0.003 s, System: 0.003 s]
```
I do agree that printing `1.006 s ±  2 ms` would be weird (and would clash with what I used to do in my physics classes). However, I would prefer reading `[User: 3.4 ms, System: 2.9 ms]`. It's on the same line, but not only this output is more informative, I also personally find it easier to read.

Using a common unit to write the `mean ± σ` and another common unit to write the user and sys time would be consistent choice. Now, it may not be a *better* one and it might just boil down to personal preferences.

**Comment by sharkdp** [comment]
Thank you for the write-up. I'm not 100% convinced that the suggested change would be for the better, so I'm tentatively closing this for now.
