### ISSUE TITLE
Increase unit test coverage

### ISSUE THREAD

**Issue by stevepentland** [sharkdp/hyperfine#54]
I was running some coverage using [cargo-kcov](https://github.com/kennytm/cargo-kcov) and noted that currently coverage on the application is somewhat low. It may be good to identify points that should be placed under test and ensure that they are. For instance, with more options being added, extracting the processing of Clap's matches to a testable function may be prudent to ensure future changes do not alter the current correct state. 

![screenshot from 2018-03-24 15-18-47](https://user-images.githubusercontent.com/8147610/37868015-b7749bee-2f76-11e8-8d10-af8350562676.png)

**Comment by sharkdp** [comment]
This would be really great. The problem is that it is quite hard to (unit-)test some of the main functionalities of `hyperfine` due to the non-deterministic nature of the benchmarks. Right now, I'm maintaining a small collection of bash scripts to do some integration-style/whole-program tests - but that's certainly not ideal.

Any ideas on how to increase the test coverage are greatly appreciated.

**Comment by stevepentland** [comment]
For sure, I'd just like to start looking at portions of the internal functionality (like clap matches -> hyperfine options) and see how we can put them under test. Some small refactors may be required, but we should be able to increase coverage on those portions that may be susceptible to inadvertent change. I was originally going to split out the parsing, but noticed that we'd probably have to do something similar to the way it is done in [fd](https://github.com/sharkdp/fd/blob/master/src/app.rs) to be able to insert the entrypoint for tests.

**Comment by sharkdp** [comment]
Sounds like a good idea. Maybe wait a few minutes, because I'm restructuring the command-line parsing code at the moment :smile:

**Comment by stevepentland** [comment]
lol, I'm not that fast. Earliest would probably be tomorrow (EST) anyway

**Comment by stevepentland** [comment]
I'm starting work on this
