### ISSUE TITLE
TERM=dumb and NO_COLOR=1 still output colours by default

### ISSUE THREAD

**Issue by nabijaczleweli** [sharkdp/hyperfine#542]
![image](https://user-images.githubusercontent.com/6709544/185815551-3cfa2a5e-3254-453f-8a96-47e51beebcaa.png)

That's invalid for the first case and [uncourteous](https://no-color.org/) for the second; compare clap that recognises the first at least.

**Comment by sharkdp** [comment]
> That's invalid for the first case and [uncourteous](https://no-color.org/) for the second

It would be nice if instead of assuming that we are deliberately non-compliant, you would have thought of the possibility that nobody yet had the time to implement this feature.
