### ISSUE TITLE
Injecting a value of a startup parameter to the output data 

### ISSUE THREAD

**Issue by dfad1ripe-bitrise** [sharkdp/hyperfine#544]
I believe it would be great to have a possibility to inject some custom key-value pair to the output data.
For example if hyperfine is run with something like below:
` hyperfine --inject-result hostname='/usr/bin/hostname' 'test command' ....`

Then the output structure would include the result of execution of that command, like for JSON:

```
{
  "results": [
    {
      "hostname": "myhost.mydomain.com",
      "command": "test command",
      "mean": 5.55555555555555,
      ....
      ....
```

This would be a great help when more than one host is tested, and the results are gathered for review.

**Comment by sharkdp** [comment]
Thank you for your request.

This is actually something that can be done already by setting a parameter that is not used in the command itself. For example, running
```bash
hyperfine -L hostname "$(hostname)" -L timestamp "$(date)" 'sleep 0.1' --export-json result.json
```
will result in a JSON file that includes the hostname and a timestamp:
```json
{
  "results": [
    {
      "command": "sleep 0.1",
      "mean": 0.10093011112137933,
      "stddev": 0.00023508060680626973,
      "median": 0.10089116388000001,
      "user": 0.0010108620689655173,
      "system": 0.0008020337931034482,
      "min": 0.10033019588,
      "max": 0.10132428988,
      "times": [ … ],
      "parameters": {
        "hostname": "floyd",
        "timestamp": "Fr 2. Sep 09:00:19 CEST 2022"
      }
    }
  ]
}
```

**Comment by gcflymoto** [comment]
@sharkdp thank you for the suggestion, these are a great workaround for "static" one-time fields determined at the beginning, but how can we do this **_during_** each benchmarked execution? For example 
`hyperfine --export-json result.json 'gzip file; <store compressed file size in result.json>; rm -f file.gz' 'xz file; <store compressed file size in result.json> rm -f file.xz'` is not ideal

1. Right now we have to store the results somewhere else, and post-process result.json to merge in the data or any other formats.
2. We cannot modify result.json while hyperfine is running? (can hyperfine release the handle before the command is run)?
3. If there were a conclude phase or a shutdown phase to *each* benchmarked command it would be more appropriate to run the extra steps there
4. We have to write N merge scripts for all the different exported formats
5. In my use case I cannot keep all the results till --cleanup of all the commands.

`hyperfine --export-json result.json --prepare 'ungzip file.gz' 'gzip file' --shutdown '<store compressed file size in result.json>' --prepare 'unxz file' 'xz file' --shutdown '<store compressed file size in result.json>'`

Thank you for an excellent tool!

**Comment by sharkdp** [comment]
To be honest, that is some very specific use case. Wanting to store metadata with the benchmarks which is *not available before the benchmark has run*.

And how would you imagine the CLI for this looks like?

**Comment by gcflymoto** [comment]
@sharkdp good question. Forgive my knowledge of the internals and history of hyperfine... Perhaps you have thought of creating "hyperfine database" of the results which is not just stored in hyperfine memory but serialized to disk. For example an embedded nosql or some other database. This could open lots of different usage models including 

* Historically keeping track of benchmarking results across invocations. 
* Generating exported formats post benchmarking
* Injecting data into the database, before benchmarking, during benchmarking, post benchmarking
* Map and reduce distributed benchmarking across thousands of machines
* Many others

I can understand this breaks software engineering paradigms of keeping hyperfine very focused on a single task and doing it very well. Perhaps this would be better in the hands of a tool written on the shoulders of hyperfine? Or tools like this have already been written using hyperfine? 

Nevertheless here goes with an _unrefined_ example

```
# Initial results database setup which does not benchmark anything, but creates the database with initial metadata
hyperfine --create-db results.db --insert-metadata userid='whoami'

# In a single benchmark written in chronological order for clarity
hyperfine --import-db results.db \
                # Added to all results in this run
                --create-metadata hostname='/usr/bin/hostname' \
                # Added to all results in this run
                --create-metadata orig_size='wc -c file'  \
                \
                'gzip file' \
                # After the command add metadata only for this benchmark 
                --benchmark-metadata compressed_size='wc -c file.gz'  \
                --shutdown 'gzip -d file.gz' \ 
                \
                'pigz file' \
                # After the command add metadata only for this benchmark 
                --benchmark-metadata compressed_size='wc -c file.gz'  \
                --shutdown 'pigz -d file.gz' \ 
                \
                'xz file' \
                # After the command add metadata only for this benchmark 
                --benchmark-metadata compressed_size='wc -c file.xz'  \
                --shutdown 'unxz file.xz' \ 
                \
                --export-db results.db

# Run additional benchmarking in parallel. The database would need support for distributed modifications
hyperfine --import-db results.db \
                # Added to all results in this run
                --create-metadata hostname='/usr/bin/hostname' \
                # Added to all results in this run
                --create-metadata orig_size='wc -c file'  \
               'zstd file' \
               --benchmark-metadata compressed_size='wc -c file.zst'
                --export-db results.db
...

# Final run to generate results only
hyperfine --import-db results.db--export-json results.json --export-csv results.csv --export-asciidoc results.asciidoc --export-markdown results.md
```

**Comment by sharkdp** [comment]
I think this is better left to external tooling.
