### ISSUE TITLE
`hyperfine` runs my program too fast

### ISSUE THREAD

**Issue by LoganDark** [sharkdp/hyperfine#558]
`hyperfine` runs my program at such a high frequency that the OS can't actually manage to unlock shared memory before the next run starts, causing an access denied error. This could be solved in two ways:

- Add an option to not run it that fast, by introducing a gap between individual runs (prevent it from erroring)
- Add an option to completely drop executions with nonzero exit codes (allow it to error, but make it not count)

Do either of those sound like good options to implement?

**Comment by sharkdp** [comment]
> Add an option to not run it that fast, by introducing a gap between individual runs (prevent it from erroring)

Would something like `--prepare "sleep 1"` work for you? (https://github.com/sharkdp/hyperfine#detailed-benchmark-flowchart)

Even better would be to run a `--prepare "…"` command that actually makes sure that the OS frees the SHM region.

> Add an option to completely drop executions with nonzero exit codes (allow it to error, but make it not count)

That can not be done currently, but you *can* use `----ignore-failure` and then export the benchmark results to JSON, which will include the exit codes as well. But that would mean you would have to do the statistical analysis yourself.

**Comment by LoganDark** [comment]
> Would something like `--prepare "sleep 1"` work for you? (https://github.com/sharkdp/hyperfine#detailed-benchmark-flowchart)

Indeed that seems to work, and actually results in more stable benchmarks for some reason.

> Even better would be to run a `--prepare "…"` command that actually makes sure that the OS frees the SHM region.

I can't unfortunately. I literally call the function to release it but then it doesn't and the kernel just kinda garbage collects it a few ms later
