### ISSUE TITLE
Citing hyperfine

### ISSUE THREAD

**Issue by jake-87** [sharkdp/hyperfine#566]
I am using hyperfine as part of a benchmarking process for a paper. How would the creators prefer it to be cited? Any format is fine, I can translate to a .bib file if needed.
Thanks in advance.

**Comment by sharkdp** [comment]
Thank you for asking! Please see this ticket: https://github.com/sharkdp/hyperfine/issues/353

We should probably add a section in the README to explain this to others in the future.

As I said in the other ticket, I'd be very happy to see the final publication/preprint!

**Comment by jake-87** [comment]
Thanks!
I'd be happy to draft up a PR for a citing guide if you want.

**Comment by jake-87** [comment]
#566

**Comment by sharkdp** [comment]
Information is now available in the sidebar.

@jake-87 Please share your publication/preprint once it's ready! :smile:

**Comment by jake-87** [comment]
Will do.
