### ISSUE TITLE
hyperfine not working with nushell

### ISSUE THREAD

**Issue by azais-corentin** [sharkdp/hyperfine#568]
Using hyperfine on Windows with nushell doesn't work properly.

Trying to benchmark ls gives me an unrecognized command error:
![image](https://user-images.githubusercontent.com/4028423/190511751-275593de-ddb2-462c-8b0e-c275d8192988.png)
This makes sense because ls is not a command on Windows with cmd.exe.

Setting the shell manually with `hyperfine -S nu 'ls' --show-output` gives me another error:
![image](https://user-images.githubusercontent.com/4028423/190512121-de413f28-dc41-4169-b0e6-70c4bb0cce6d.png)

nushell only supports running commands using `nu -c`.

**Comment by sharkdp** [comment]
Thank you for reporting this. That is unfortunate. Do you have any ideas on how to resolve this?

**Comment by FilipAndersson245** [comment]
fixed in #582, looked like it always defaulted to cmd.exe style of shell on windows, now the default should be `-c` when not in cmd.exe
