### ISSUE TITLE
ARM64 Windows binaries

### ISSUE THREAD

**Issue by rashil2000** [sharkdp/hyperfine#569]
Hi! 

I would like to use hyperfine on a Windows ARM server for running benchmarks. Since performance is important here, I think it will be better to run ARM64 natively rather than using x86_64 emulation. 

Ref: [starship](https://github.com/starship/starship/blob/master/.github/workflows/release.yml) provides ARM64 binaries as part of their releases. They are built using GitHub Actions.

**Comment by sharkdp** [comment]
Is that the aarch64-pc-windows-msvc target? Sure, we could simply try to add that in the `.github/workflows/CICD.yml` file. Feel free to open a PR.

**Comment by sharkdp** [comment]
I'm afraid it's not really possible to set this up in CI (see #621). You will probably have to compile natively on your host. See instructions here: https://github.com/sharkdp/hyperfine#with-cargo-linux-macos-windows



> Since performance is important here, I think it will be better to run ARM64 natively rather than using x86_64 emulation.

It's probably important that the application that you are benchmarking is a native one. But it might be okay to run hyperfine with x86_64 emulation.
