### ISSUE TITLE
Ability to analyze the time output by shell commands

### ISSUE THREAD

**Issue by countvajhula** [sharkdp/hyperfine#571]
Thanks for this great tool. There are times when I'd like to use it to analyze the time reported by measurements that aren't themselves shell commands, but, commonly, programs within some language ecosystem such as python. These measurements are runnable via scripts written in that language that produce the measured time as output. That is, the time of interest in these cases is not the time taken by the script but the _output of the script_.

It would be great to be able to use hyperfine do its usual multiple runs and statistical analysis on this produced result. For instance, say there's a script `measure.rkt` written in some language (e.g. Racket, in this case) which outputs a measured value. Typically, I'd run it like this:

```
$ ./measure.rkt some arguments
192

$ ./measure.rkt some arguments
198

$ ./measure.rkt some arguments
201

$ ./measure.rkt some arguments
163
```

After running this N times, I either form a mental average from eyeballing the results, or copy the output and process the results manually using some programming language.

Instead, it would be great to be able to pass a flag to hyperfine that would allow it to run its analysis using the output of the command instead of performing an independent measurement. For example:

```
$ hyperfine --use-output "./measure.rkt some arguments"

Benchmark 1: measure.rkt some arguments
  Time (mean ± σ):     171.5 ms ±  11.5 ms
  Range (min … max):   163.4 ms … 214.5 ms    17 runs
```
(just an example)

This could also support any shell processing prior to hyperfine using the results, lending the flexibility to use hyperfine in a lot of different settings. For instance, if the output of `measure.rkt` is something like `232 ms` instead of just `232`, we could use it as:

```
$ hyperfine --use-stdout "./measure.rkt some arguments | grep -o \"[0-9]\+\""
```

Note: I tried using something like this:

```
# sleep for the number of seconds reported by measure.rkt
$ hyperfine "./measure.rkt | grep -o \"[0-9]\+\" | sed s/^/0./ |xargs sleep"
```

But this doesn't do what we want because it includes the cost of running the script and all the commands in the shell pipeline, and not just the final stage in the pipeline.

**Comment by sharkdp** [comment]
please see #370 and #170
