### ISSUE TITLE
apt package for Debian/Ubuntu?

### ISSUE THREAD

**Issue by tstackhouse** [sharkdp/hyperfine#585]
This looks like a great tool, but it's a little weird that it's seemingly available in every package manager except `apt`, any chance of publishing a package there so an install/update is just an `apt install hyperfine` away?

**Comment by sharkdp** [comment]
Thank you for the feedback.

I think it's already in Debian (https://packages.debian.org/unstable/utils/hyperfine), so it might end up in Ubuntu soon. But for details, you would have to contact the Ubuntu package maintainers. I'm personally not going to work on packaging.
