### ISSUE TITLE
Hyperfine loads indefinitely, only continues when pressing ctrl-c

### ISSUE THREAD

**Issue by tim-hilt** [sharkdp/hyperfine#588]
Unfortunately I can't really give a reproducible example for this, as the command I wanted to profile is [a cli that I wrote myself](https://github.com/tim-hilt/tempo).

What could be the cause of hyperfine blocking until the user presses ctrl-c?

**Comment by sharkdp** [comment]
Can you try with `--show-output`?

**Comment by tim-hilt** [comment]
Oh, that worked! Any idea, why that is? Do I have to build something in a different way in my tool?

**Comment by sharkdp** [comment]
Wait.. what do you mean "that worked"? :smile: 

I was imagining that this would only tell you why it blocks. If the benchmarking works fine with `--show-output`, but not without, then your program reacts differently when the output is piped or not.

So you could try to run `my-program > /dev/null` (or maybe `my-program | cat`) vs `my-program` and see if there are any differences there as well.

**Comment by tim-hilt** [comment]
Interesting! I meant that as in „benchmark ran whilst showing output of my logs“. In the end it showed a mean of around one second.

The benchmark wasn’t completed before. It was showing an empty progress-bar and the spinner was running indefinitely. I installed the stable version via pacman (Arch).

I‘m currently not on my computer - but any more things I could try / infos I could provide? I’ll be sure to check back tomorrow.

**Comment by tim-hilt** [comment]
PS: didn‘t read the last paragraph. I did check >/dev/null, since I thought the output could be the problem. I’ll try again with piping to cat.

**Comment by tim-hilt** [comment]
@sharkdp My cli also blocks when I redirect to `>/dev/null`. No idea why, but it seems not to be an issue with hyperfine. If you still want hyperfine to correctly handle cases like mine we can keep this issue open and I'll come back to it as soon as I find out something new.

**Comment by sharkdp** [comment]
I think we can close it, but I'd be interested in hearing about the conclusion. If I understand correctly, there's nothing that hyperfine could to to help with that. If your program blocks, how would we know?
