### ISSUE TITLE
Manycore support

### ISSUE THREAD

**Issue by chadbrewbaker** [sharkdp/hyperfine#593]
I was thinking of adding support for testing large core counts where you have non-uniform cache/IO topology.

Use cases like @axboe where you want to know which two cores best route IO.

https://mobile.twitter.com/axboe/status/1602456528535302145

I was thinking of using openmpi as the the driver to pin the cores, then run the test. What is a good syntax?

I was thinking of an explicit core transformation (repeats allowed, you can assign more than one process to the same  core), whatever the OS decides, random, and the mpirun ordering options?

Galaxy brain I was even thinking of a GNU parallel driver so you could ssh to several machines too? Even allow for [Coz](https://github.com/plasma-umass/coz) style delay adding experiments to elicit bottlenecks?

```bash
# This works now
hyperfine 'mpirun -np 8 ./a.out'
hyperfine 'parallel a.out ::: {1..8}'
```

Double galaxy brain, have it also do hyper-parameter tuning like setting compiler flags, not just setting CPU topology. Should be able to use [Vizer](https://github.com/google/vizier) as a black box. Just need a TOML file to read the allowed parameters from.

Thinking of adding this as a Python3 driver script. Then once the interface is figured out re-write in proper Rust.

**Comment by sharkdp** [comment]
I'm sorry, but I can't really follow. You talk about many (unrelated?) things, and I don't really know what you're asking specifically?



> Double galaxy brain, have it also do hyper-parameter tuning

See https://github.com/sharkdp/hyperfine/issues/320
