### ISSUE TITLE
Compile failure on FreeBSD

### ISSUE THREAD

**Issue by neersighted** [sharkdp/hyperfine#60]
This is due to an upstream bug in console, which I have a pending PR against here: https://github.com/mitsuhiko/console/pull/5

On FreeBSD, `ioctl()` accepts a u64. However, `TIOCGWINSZ` is defined as a u32.

**Comment by sharkdp** [comment]
Thank you!

Keeping this open until this has been fixed upstream.

**Comment by sharkdp** [comment]
We should be able to fix this now.

**Comment by sharkdp** [comment]
@Freaky Thanks!

So we don't even have to upgrade the `console` dependency?

**Comment by Freaky** [comment]
No, `Cargo.lock` still needs updating so a normal `build` from source works.

Seems that including it in a published crate is an [opt-in unstable feature](https://doc.rust-lang.org/cargo/reference/unstable.html#publish-lockfile).

**Comment by sharkdp** [comment]
Thank you.

I have updated the dependencies, so this should be fixed with the next release.

**Comment by sharkdp** [comment]
Hopefully fixed in https://github.com/sharkdp/hyperfine/releases/tag/v1.3.0

**Comment by Freaky** [comment]
Looks good, builds from source and from cargo with both stable and nightly Rust on FreeBSD 11.2/amd64.
