### ISSUE TITLE
Sort output markdown results by Relative column (ascending)

### ISSUE THREAD

**Issue by SUPERCILEX** [sharkdp/hyperfine#601]
The first row would be 1.00 and then you grow from there. That'd make the results easier to interpret.

**Comment by sharkdp** [comment]
Thank you for your request. I usually like to see the benchmarks in the order that I entered them. I'm not convinced that this should be the new default.

**Comment by SUPERCILEX** [comment]
I feel like the current default leans towards answering the wrong question: *how fast is X?* When you sort by time, the question more easily becomes *how fast is X relative to Y?*

**Comment by sharkdp** [comment]
I'm closing this in favor of #614. Thank you

**Comment by sharkdp** [comment]
This is now supported in https://github.com/sharkdp/hyperfine/releases/tag/v0.17.0
