### ISSUE TITLE
Include user and system time in exports 

### ISSUE THREAD

**Issue by SUPERCILEX** [sharkdp/hyperfine#602]
These are useful as a measure of efficiency when timings are similar.

**Comment by sharkdp** [comment]
We do export user and system times to JSON. But I'd rather not add them to the markup exports. At least not by default. I often post Markdown tables to GitHub issues and they are already wide enough.

We *can* think about adding optional support for this, but I'd first like to see a proposal on how the CLI should look like: what kind of new option do we introduce? A simple flag like `--add-user-and-system-time-…` or something more future-proof like `--export-options=add-user-and-system-time` which can be extended with more options?

Please note that I'm not yet convinced that we should add this at all.

**Comment by SUPERCILEX** [comment]
Yeah, my use case is pretty niche, so honestly having the code in my own fork might be good enough. I'm using it as a measure of efficiency: if two commands take about the same time to run, but one of them uses way more system time, then that one is worse. That said, I can see how a single threaded CPU bound application would find this useless because all the time goes into the User bucket and matches the mean.

I think the export-options flag you suggested makes sense.

**Comment by sharkdp** [comment]
Thank you for the explanation. I think I'd like to close this for now. We can come back to it if others have similar needs.
