### ISSUE TITLE
Support `-` as shorthand for stdout for output

### ISSUE THREAD

**Issue by horenmar** [sharkdp/hyperfine#615]
Related to my other issue, I tried using `--export-markdown -` to get the markdown output shown immediately in stdout. To my surprise, I ended up with a file named `-`.

Since using `-` for stdout/stderr is relatively common convention, I would like it to be supported for the output options as well.

**Comment by sharkdp** [comment]
I use `--export-markdown /dev/stdout`, but supporting `-` sounds good. Thank you for the suggestion.
