### ISSUE TITLE
Heads-up: I package Hyperfine scripts in a Homebrew tap

### ISSUE THREAD

**Issue by 0mp** [sharkdp/hyperfine#617]
Hey! I just wanted to let you know that I packaged the data analysis scripts from the `scripts` directory in a Homebrew tap for macOS: https://github.com/0mp/homebrew-essentials

The tap takes care of the Python dependencies, so that you don't need to install them on your own system-wide with pip or in a virtual environment.

Cheers!

**Comment by sharkdp** [comment]
Thank you. If you want, you can add a short paragraph + install command here https://github.com/sharkdp/hyperfine#on-macos
