### ISSUE TITLE
Question about hyperfine benchmark results

### ISSUE THREAD

**Issue by Pavel-Durov** [sharkdp/hyperfine#665]
I was looking at hyperfine documentation but I couldn't find anything related to the the output format.

How do I read hyperfine benchmark results?

Example:
```shell
  Time (mean ± σ):      14.9 ms ±   0.7 ms    [User: 12.5 ms, System: 2.3 ms]
  Range (min … max):    14.0 ms …  21.3 ms    187 runs
```
`min .. max` - minimum and maximum running times
`User` - time spent in user space, amount of time spent on the program itself
`System` - time spent in system space, amount of time spent on OS functions related to the program
`runs` -  total count of benchmark runs

What's `mean ± σ`?  Standard deviation?

**Comment by Pavel-Durov** [comment]
The way I interpret it:

`mean` -  is the average execution time of the benchmarks
`± σ` - is the standard deviation representing the amount of variation from the mean

Is it somehow correct?

**Comment by sharkdp** [comment]
Please see #443

**Comment by sharkdp** [comment]
@Pavel-Durov does this help?
