### ISSUE TITLE
Parameters don't get expanded in preparation commands

### ISSUE THREAD

**Issue by lava** [sharkdp/hyperfine#67]
It seems like parameters are only substituted for the actual command, not the preparation command:

    $ hyperfine -P X 1 10 -p 'python -c "print 2**{X}"' --show-output -- ls
    Benchmark #1: ls
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    NameError: name 'X' is not defined
    Error: The preparation command terminated with a non-zero exit code. Append ' || true' to the command     if you are sure that this can be ignored.

**Comment by sharkdp** [comment]
Thank you for reporting this. It looks like this is definitely worth adding.
