### ISSUE TITLE
Add quieter markdown `stdout` export

### ISSUE THREAD

**Issue by Neved4** [sharkdp/hyperfine#685]
Currently, `hyperfine` allows markdown export to `stdout` with `--export-markdown -`. This also includes its regular output, requiring manual filtering.

### Feature request

- Add flag to suppress `hyperfine`'s regular output.  
  
  As `--quiet` would be vague in this context, consider something like `--minimal-output, -qm`  
  or `--low-verbosity, -ql`.

### Background

When running multiple benchmarks to later be unified in a single markdown file, one needs to call `hyperfine` and create intermediate files, to later structure the saved outputs in an unified manner, cleaning the intermediates:
```sh
# temp.sh

hyperfine 'echo 1' --export-markdown first.md
hyperfine 'echo 2' --export-markdown second.md

printf '%s\n' '## First benchmark'
cat first.md > bench.md

printf '%s\n' '## First benchmark'
cat second.md > bench.md

rm first.md second.md
```

Alternatively, since `hyperfine` allows to export to `stdout` instead, we can get rid of the temporary files and filter the desired output:
```sh
# filter.sh

filter() {
    awk '/^\| Command | Mean /{p=1} p && !/^$/{print} p && /^$/{exit}'
}

{
    printf '%s\n' '## First benchmark'
    hyperfine 'echo 1' --export-markdown | filter

    printf '%s\n' '## Second benchmark'
    hyperfine 'echo 2' --export-markdown - | filter
} > bench.md
```

See: [tukosmo-errhandle/b795a31](https://github.com/Neved4/tukosmo-errhandle/commit/b795a31d85aa0297f2a66ae7adc168c0c5bb1ab2)

Overall this streamlined approach avoids temporary files, although in other scenarios the ability to suppress the regular output entirely can be more suitable, removing the need of a filtering function.

**Comment by sharkdp** [comment]
Did you see the `--style` option? In particular: `--style=none`

**Comment by Neved4** [comment]
@sharkdp Spot on. Thanks!

Missed that, the manpage description can be a bit misleading:
> Set this to 'none' to disable _**all the output**_ of the tool.

Closing.
