### ISSUE TITLE
Add short flag counterparts

### ISSUE THREAD

**Issue by Neved4** [sharkdp/hyperfine#689]
Short flags enhance brevity and conciseness.
Currently, some options lack equivalent short flags to invoke them:

- [X] `-w`, `--warmup`
- [X] `-m`, `--min-runs`
- [X] `-M`, `--max-runs`
- [X] `-r`, `--runs`
- [X] `-s`, `--setup`
- [X] `-p`, `--prepare`
- [X] `-c`, `--cleanup`
- [X] `-P`, `--parameter-scan`
- [X] `-D`, `--parameter-step-size`
- [X] `-L`, `--parameter-list`
- [X] `-S`, `--shell`
- [X] `-N`, (alias for '--shell=none')
- [X] `-i`, `--ignore-failure`
- [ ] `-l`, `--style`
- [ ] `-t`, `--sort`
- [X] `-u`, `--time-unit`
- [ ] `-d`, `--show-output`
- [ ] `-O`, `--output`
- [ ] `-I`, `--input`
- [X] `-n`, `--command-name`
- [X] `-h`, `--help`
- [X] `-V`, `--version`

###### Since `--export` variants lend themselves to further discussion they are tracked in https://github.com/sharkdp/hyperfine/issues/691

**Comment by sharkdp** [comment]
Missing short options in the CLI are not a matter of neglect. They were left out because those options were not considered to be used frequently. Out of the ones listed, only `--show-output` is something that I personally use frequently. What do others think?

**Comment by sharkdp** [comment]
Closing this for now. If someone thinks a particular option deserves a short option, let us know.
