### ISSUE TITLE
Please bump the version of the csv dependency

### ISSUE THREAD

**Issue by paride** [sharkdp/hyperfine#69]
csv 1.0.0 is out, but hyperfile still depends in the beta version. Pease bump the dependency. This will help downstream (Debian) packaging.

**Comment by sharkdp** [comment]
I'm curious: Packaging for a particular distribution?

We do provide Debian packages on the Releases page.

That being said, I'm okay with bumping the dependency version for csv.

**Comment by paride** [comment]
Packaging for Debian :)
I mean: maintaining a package in the official Debian repository.

**Comment by sharkdp** [comment]
Wow, this is great to hear! Is there a ticket/thread for this somewhere? I'd love to follow the progress on that.

I totally forgot that we were on a beta version of the `csv` crate and definitely to upgrade to 1.0.0 as soon as it was released.

Closed via 94621ad.

**Comment by paride** [comment]
Not really a thread, most of the Rust packaging work is being done here:

https://salsa.debian.org/rust-team/debcargo-conf

but before a package can be uploaded all its dependencies need to be already in Debian, so there is a lot to do!

I also plan to package fd and sad, but unfortunately I'll have to rename them, as other packages already install `/usr/bin/fd` and `/usr/bin/sad` (and the relative manpages).

**Comment by sharkdp** [comment]
Thank you very much!

I just released v1.2.0 with the fix.

> I also plan to package fd and sad, but unfortunately I'll have to rename them, as other packages already install /usr/bin/fd and /usr/bin/sad (and the relative manpages).

It would be really great to see `fd` in Debian! Instead of renaming the executables, does Debian provide a way to mark two packages as conflicting? Or does it follow other policies in this respect?

What is `sad`?

**Comment by FranklinYu** [comment]
@paride Hi, is Hyperfine currently packaged in Debian official repository? I don’t see Debian on Repology of this package. I did find `fd-find` though.

**Comment by paride** [comment]
Hi,

hyperfine is not packaged in Debian yet. There was a packaging attempt but from this file:

https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/hyperfine/debian/BLOCK

looks like it's blocked by missing dependencies.

**Comment by FranklinYu** [comment]
You should have used a permanent link, because now the file is gone in master branch. 😄 

https://salsa.debian.org/rust-team/debcargo-conf/-/blob/601671abe39610405e0c394d2f8e51c5325a27a8/src/hyperfine/debian/RFS

**Comment by FranklinYu** [comment]
See latest update in https://tracker.debian.org/pkg/rust-hyperfine. TL;DR not yet in stable, won’t be in Bullseye (Debian 11).
