### ISSUE TITLE
Usage of `hyperfine` to benchmark code

### ISSUE THREAD

**Issue by femtomc** [sharkdp/hyperfine#694]
Hi all! First, I love this package - it's been super useful for me at the command line.

Second: I'd love to use this package to benchmark _running code_ e.g. in Python. I suspect this is out of scope for this package to support, but I'd be interested in setting up bindings (or something similar) in an external repo that uses `hyperfine`.

Is there a sense in whether this would be easy or hard to do?

**Comment by sharkdp** [comment]
Thank you for the feedback.


Please see #135, #153, #170
