### ISSUE TITLE
ETA not clearly visible on terminals with a block cursor

### ISSUE THREAD

**Issue by overclockworked64** [sharkdp/hyperfine#698]
I'm having an issue seeing ETA clearly on my terminal with a block cursor:

![tUkUtGd](https://github.com/sharkdp/hyperfine/assets/92276115/40a9c3f2-12f6-4c5c-b36c-f64213a9e481)

I imagine the character where the cursor is gets printed last, so the cursor just stays there. I don't mean to nitpick, and maybe it's just my eyes, but IMO, it would be nice if ETA was visible in its entirety with no cursor on top of it.

btw. great software! :-)

**Comment by sharkdp** [comment]
Thank you for reporting this. I think it should be easy to fix by adding a space at the end of our progress bar template.
