### ISSUE TITLE
Always in this "Initial time measurement" state

### ISSUE THREAD

**Issue by Lzzzs** [sharkdp/hyperfine#703]
I executed **“npx craco start --mode development”** , it stays in this "Initial time measurement" state.

![Snipaste_2023-11-01_20-00-01](https://github.com/sharkdp/hyperfine/assets/74575471/a5e9d61d-bab4-407c-837d-9cfc0f8b2d04)

**Comment by sharkdp** [comment]
Maybe the program is waiting for input? Can you run with `--show-output`?

**Comment by Lzzzs** [comment]
> Maybe the program is waiting for input? Can you run it with `--show-output`?

Is it because I'm starting a webpack service and it's waiting for my input? How can I solve this situation

Execute this command “yarn start:bench"
![image](https://github.com/sharkdp/hyperfine/assets/74575471/325e5a11-27cf-4434-91fa-4f4b58098f0d)

**Comment by sharkdp** [comment]
what happens if you simply run `npx craco start --mode development` on the terminal? What happens if you run `hyperfine --show-output "npx craco start --mode development"`?

**Comment by Lzzzs** [comment]
run `npx craco start --mode development` or `hyperfine --show-output "npx craco start --mode development`  have the same result. They will both start webpack serve

**Comment by sharkdp** [comment]
If this runs indefinitely, then what do you want to benchmark?

**Comment by Lzzzs** [comment]
I want to benchmark based on webpack startup time.
