### ISSUE TITLE
`-N` makes me can't pass options for command which'll be benchmarked.

### ISSUE THREAD

**Issue by luceat-lux-vestra** [sharkdp/hyperfine#710]
https://github.com/SUPERCILEX/fuc/issues/29#issuecomment-1845182631

On windows.

with `-N`, It doesn't work.
>hyperfine --warmup 3 -N --show-output --prepare "ftzz g -n 100 -b 100 ""D:/tmp/ftzz""" "rmdir /S /Q ""D:/tmp"""

without `-N`, It works fine.

>hyperfine --warmup 3 --show-output --prepare "ftzz g -n 100 -b 100 ""D:/tmp/ftzz""" "rmdir /S /Q ""D:/tmp"""

Thanks.

**Comment by sharkdp** [comment]
This looks like some kind of quoting error. Note that the argument parsing is limited when you are using `-N`.
