### ISSUE TITLE
hyperfine consistently measures short outlier that I cannot reproduce in the wild

### ISSUE THREAD

**Issue by RalfJung** [sharkdp/hyperfine#72]
I am trying to measure an incremental compilation benchmark (to reproduce something coming up on perf.rust-lang.org). Hyperfine consistently reports "Range (min … max):    11.0 ms … 765.1 ms" and "Time (mean ± σ):     590.1 ms ± 304.8 ms", which is effectively a useless result (it doesn't print a warning though, but still). However, when I time the same command myself (`cargo` prints the time and I also tried `time`), I never see anything below 700ms.

So my suspicion is that this 11ms result hyperfine is seeing is somehow caused by not calling the benchmark correctly, but I do not know how that could happen either.

To reproduce, clone https://github.com/rust-lang-nursery/rustc-perf/ and go to `collector/benchmarks/coercions`. Do an initial `cargo +nightly build` to fill the incremental cache. Now run `touch src/main.rs && cargo +nightly build` many times; for me it is pretty stable between 730ms and 770ms.

Now run
```
hyperfine -w 2 -p "touch src/main.rs" "cargo +nightly build"
```
This shows a range from 10ms to 790ms. Something is clearly odd -- but it's not `-p`, because
```
hyperfine -w 2 "touch src/main.rs && cargo +nightly build"
```
has all the same problems.

**Comment by RalfJung** [comment]
Oh... I think I got it...

When the command runs twice within the same second, `touch` is not enough to "taint" the cache. Ouch.

**Comment by sharkdp** [comment]
Thank you for the feedback, glad you figured it out.

`hyperfine -w 2 -p "touch src/main.rs && sleep 1" "cargo +nightly build"` ? :smile:


For future reference: It can be helpful to use `hyperfine`'s `--show-output` option to debug:
```
▶ hyperfine -w 2 -p "touch src/main.rs" "cargo +nightly build" --show-output

Benchmark #1: cargo +nightly build

   Compiling issue-32278-big-array-of-strings v0.1.0 (file:///tmp/rustc-perf/collector/benchmarks/coercions)
    Finished dev [unoptimized + debuginfo] target(s) in 0.84s
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s                                             
   Compiling issue-32278-big-array-of-strings v0.1.0 (file:///tmp/rustc-perf/collector/benchmarks/coercions)
    Finished dev [unoptimized + debuginfo] target(s) in 0.82s
   Compiling issue-32278-big-array-of-strings v0.1.0 (file:///tmp/rustc-perf/collector/benchmarks/coercions)

[...]
```
