### ISSUE TITLE
Provide Statically Compiled Binaries for (aarch64|arm64) Linux

### ISSUE THREAD

**Issue by Azathothas** [sharkdp/hyperfine#723]
Hi, sorry for spamming.
See: 
https://github.com/sharkdp/bat/issues/2863
https://github.com/sharkdp/hexyl/issues/217
For Hyperfine: https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/aarch64_Linux/bins/hyperfine.sh

The same applies for the rest of your tools, if it's possible, please provide musl based (aarch64|arm64) Linux binaries.

**Comment by sharkdp** [comment]
I'd rather not pull in external dependencies / scripts just for building binaries. But if someone wants to add that target in CICD.yml, please go ahead.
