### ISSUE TITLE
Distribution via NPM

### ISSUE THREAD

**Issue by jerrygreen** [sharkdp/hyperfine#737]
I’d like to see hyperfine distributed via NPM:

https://www.npmjs.com/hyperfine

Probably compile to WebAssembly? To make it possible? I’m not sure how the guy there made it.

Btw, it is possible to write to npm for asking to taking slug url like this, they often give away the names to their respective authors.

> UPD. Actually I see how he made it. It seems, the package simply downloads the latest binaries. It doesn’t take VERSION into consideration. It’s too bad. But maybe it’s possible to adjust his script, and pair version on npm to hyperfine – instead of doing WebAssembly. This way, I can lock both: the version of a tool I’m making, with the bench tool itself. That’d be good.

**Comment by sharkdp** [comment]
> I’d like to see hyperfine distributed via NPM:

Can I ask why?

**Comment by jerrygreen** [comment]
Because it's convenient way to install anything
Because npm community makes A LOT of cli tools
Because hyperfine benchmarks cli-tools

I just was searching for such a tool to test my cli-tool, and I searched all bench utils on npm.
It's not something blocking me to use hyperfine of course, since I already somehow got here.
But it might be good way to gain some more other users.

**Comment by dalisoft** [comment]
@jerrygreen Maybe [this package](https://github.com/dalisoft/binary2npm) can help you? Because i'm used it on my projects for using as `npm` package

**Comment by sharkdp** [comment]
If someone wants do do this, please go ahead. But I'm not going to invest time into this.
