### ISSUE TITLE
hyperfine as library

### ISSUE THREAD

**Issue by nichmor** [sharkdp/hyperfine#747]
Hello!

I tried to find similar issue but without success. Sorry if it's a duplicate.

Are there any plans ( or will you accept ) support of hyperfine as library ( adding some exports in lib.rs ) ?
This will allow to use hyperfine as building blocks for other tools.

Thanks!

**Comment by sharkdp** [comment]
Thank you for your request. There is a similar request here: #367, but with a more limited scope (I guess). I would probably not invest a lot of time myself into designing hyperfine-as-a-library, but I would accept PRs to work in this direction (multiple small PRs would be very welcome). Especially if it helps with proper modularization of the codebase.
