### ISSUE TITLE
hyperfine pre-built binary for macOS ARM (M1/M2/M3)

### ISSUE THREAD

**Issue by Zabrane** [sharkdp/hyperfine#760]
Hi guys

Would it be possible to generate a pre-built binary for `macOS ARM (M1/M2/M3)`?
Many thanks and keep up the good work.

Best

**Comment by Successs01** [comment]
https://www.fiverr.com/s/zWydGpb
I'n here I have the a bot called a trading bot that trade in all exchanges for you with just a click the bot will go to another exchange and trade for you ...

**Comment by sharkdp** [comment]
I think this should be included via https://github.com/sharkdp/hyperfine/pull/728

**Comment by sharkdp** [comment]
https://github.com/sharkdp/hyperfine/releases/tag/v1.19.0

**Comment by Zabrane** [comment]
@sharkdp thanks a lot.
