### ISSUE TITLE
Can't measure time until Neovim UIEnter event

### ISSUE THREAD

**Issue by delphinus** [sharkdp/hyperfine#765]
Neovim raises some events in its startup, such as `VimEnter` and `UIEnter`. Some plugins (ex. [nvimdev/dashboard-nvim](https://github.com/nvimdev/dashboard-nvim)) makes itself launch in `UIEnter`, so I tried to measure launching time with them, and failed.

In investigation, I noticed Neovim launched by hyperfine does not raise `UIEnter` event.

```bash
# This measures time until VimEnter event.
$ hyperfine 'nvim --clean +"au VimEnter * q"'
Benchmark 1: nvim --clean +"au VimEnter * q"
  Time (mean ± σ):      15.0 ms ±   1.5 ms    [User: 6.2 ms, System: 3.9 ms]
  Range (min … max):    11.1 ms …  18.1 ms    117 runs

# This measures time until UIEnter event.
$ hyperfine 'nvim --clean +"au UIEnter * q"'
Benchmark 1: nvim --clean +"au UIEnter * q"
 ⠙ Initial time measurement       ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ ETA 00:00:00

# ……??
```

I tested this in Neovim 0.10.1 and HEAD.

The result above shows Neovim under hyperfine raises `VimEnter`, but not `UIEnter`. How do we fix this?

**Comment by sharkdp** [comment]
Take a look at hyperfine's `--output` option. And maybe try with `--output=inherit`.

**Comment by delphinus** [comment]
Thank you! `--output inherit` makes all good.

```bash
$ hyperfine -w 10 --output inherit "nvim --clean +'au VimEnter * q'" "nvim --clean +'au UIEnter * q'"
Benchmark 1: nvim --clean +'au VimEnter * q'
  Time (mean ± σ):      20.3 ms ±   0.3 ms    [User: 11.6 ms, System: 7.7 ms]
  Range (min … max):    19.5 ms …  21.6 ms    128 runs

Benchmark 2: nvim --clean +'au UIEnter * q'
  Time (mean ± σ):      20.4 ms ±   0.3 ms    [User: 11.6 ms, System: 7.7 ms]
  Range (min … max):    19.8 ms …  21.3 ms    126 runs

Summary
  nvim --clean +'au VimEnter * q' ran
    1.00 ± 0.02 times faster than nvim --clean +'au UIEnter * q'
```

In benchmarking, the display flushes many times because of showing Neovim's startup window, maybe. And the result seems valid as I have expected.
