### ISSUE TITLE
Output number of runs

### ISSUE THREAD

**Issue by orium** [sharkdp/hyperfine#78]
It would be nice, by default, to know how many runs hyperfine did for a benchmark.

**Comment by orium** [comment]
I would say it is an important metric for any benchmark.  For example, it will give you confidence in the standard deviation: if your there were 10 iterations you can say you are somewhat confident on the numbers; if it ran 1000 times you will be very confident.

**Comment by sharkdp** [comment]
Okay, sounds good. I would like to gray it out, though. Or maybe we should consider adding something like a `--verbose`/`--detailed`/.. option that shows some additional information.
