### ISSUE TITLE
Provide preparation command to be run between benchmarking different commands

### ISSUE THREAD

**Issue by RalfJung** [sharkdp/hyperfine#91]
I want to benchmark two versions of `rustc` against each other, measuring the build time of a project that however has some build dependencies, downloading and building which I do not want included in the benchmark.  However, after using one version of rustc, I need to `rm -rf target` to enable the other one to build; these are both self-compiled git versions of Rust and their detection of when to recompile because the compiler changed does not work reliably.

Unfortunately, this is not possible with one hyperfine invocation currently; instead I have to resort to calling hyperfine twice and clean the build dir in between. It would be great if hyperfine had a preparation command that was run in-between different commands being benchmarked, but NOT in-between different runs of the same benchmark.

**Comment by sharkdp** [comment]
Thank you for the feedback!

Sounds like a good idea to me.

**Comment by sharkdp** [comment]
Fixed via #129 by @colinwahl

**Comment by sharkdp** [comment]
Released in [v1.6.0](https://github.com/sharkdp/hyperfine/releases/tag/v1.6.0).
