### ISSUE TITLE
Test Performace per Watt

### ISSUE THREAD

**Issue by MatheusRV** [sharkdp/hyperfine#92]
As user @mitchtbaum raised the questioning, I believe it would be interesting to discuss the implementation of an evaluation regarding Performace Por Watt. What the community think? The implementation of PowerAPI does not seem very feasible for HyperFine, since it is implemented in Scala. I do not know, I do not know well about functional languages but I love and use the benchmarks in my scientific life.

Related:
https://github.com/TechEmpower/FrameworkBenchmarks/issues/4117

**Comment by sharkdp** [comment]
I would like to keep hyperfine focused on time-based benchmarks. Adding other metrics such as memory usage or energy usage is out of the scope for this project.
