### ISSUE TITLE
Disable Warning

### ISSUE THREAD

**Issue by akvadrako** [sharkdp/hyperfine#94]
I can't figure out a way to remove this warning:

```
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
```

I don't want any warmups but I have tried using the argument anyway.

**Comment by sharkdp** [comment]
Thank you for the feedback.

Can you tell me more about the program you are trying to benchmark? Does it have a non-deterministic component that might could lead to outliers?

Did you try to use more benchmarking runs (`hyperfine --min-runs N`)?

Did you really shut down all processes that might affect the benchmarks? If I am benchmarking I/O-heavy programs, I always make sure to close spotify, dropbox, browser, etc.

If none of this works, there is still a possibility that the outlier-detection reports false positives. In this case, just look at the standard deviation and min..max outputs and decide for yourself if you are satisfied with the results. The outlier-detection is just a simple heuristic to detect cases where something is clearly interfering with the benchmark (other processes or a caching effect).

**Comment by akvadrako** [comment]
Hi David,

What I'm benchmarking is pretty simple - it's some AWS calls. They don't always take the same amount of time. But also, I'm interested in outliers, especially the first call. The warning just makes the results harder to read.

**Comment by sharkdp** [comment]
I see.

The "outlier" results are never removed, so they are always present in the results. It's only the warning.

If you are interesting in removing the warning from the output, you can simply redirect `stderr` to `/dev/null`:
```
hyperfine my-program 2> /dev/null
```

Unfortunately, this seems to disable the interactive output (progress bars) even if we specify `--style=full`.

**Comment by sharkdp** [comment]
Closing this, as there is no update.
